### ISSUE TITLE
Collision config doesn't function properly when right-clicking entities

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Sponge#1005]
Currently, `MixinChunk_Collisions` just uses the source `BlockSnapshot` or `Entity` in the current `PhaseContext` to determine what collisions to perform. However, this can lead to issues when interacting with mod items, such as in [this issue](https://github.com/SpongePowered/SpongeForge/issues/1000#issuecomment-257101497). Our collision system will see the source entity as a `Player`, rather than the entity being interacted with.

I suggest that we delegate determination of the active entity to `IPhaseState`. It will default to returning the source entity or blocksnapshot, but will be overridden in `InteractionPacketState` to use the target entity or block.

Pinging @bloodmc for input.

**Comment by ryantheleach** [comment]
@Aaron1011 Do you know if this is still relevant?

Given the mob entity cramming rules that Mojang have introduced, is the collision patch still as useful as it was?

**Comment by ImMorpheus** [comment]
This should be fixed by https://github.com/SpongePowered/SpongeCommon/pull/2453

`InteractionPacketState` now inherits `isCollision` from `IPhaseState`
https://github.com/SpongePowered/SpongeCommon/blob/bafbfa0a6849bee99d6fd1c0b8f563e5fb1bee35/src/main/java/org/spongepowered/common/event/tracking/IPhaseState.java#L528-L530

Which is making the method return early here
https://github.com/SpongePowered/SpongeCommon/blob/bafbfa0a6849bee99d6fd1c0b8f563e5fb1bee35/src/main/java/org/spongepowered/common/mixin/entitycollisions/ChunkMixin_Collisions.java#L88

This is valid for all `Phasestate`s since they all have `isCollision` returning false (except `EntityCollisionState`)
