### ISSUE TITLE
ResourcePackStatusEvent not firing.

### ISSUE THREAD

**Issue by Proxying** [SpongePowered/Sponge#1057]
It seems that the ResourcePackStatusEvent is not firing at all upon player joining. Example here; I've set my clientside resourcepack information to force the server to prompt me for the resource pack, my selection should fire the event. Nothing appears in chat from the initial broadcast, and upon declining it, the player is not kicked.

Code here;
http://hastebin.com/ujehawerar.cs

SpongeForge 1.10.2 v 1965.

**Comment by Cybermaxke** [comment]
Try to remove the `@Root Player player` argument from the method,  it's probably not provided in the cause because it's already directly provided through the event `getPlayer`.

**Comment by Proxying** [comment]
Removing that has no effect, that's what I initially was running, tried to add it to see if it'd change anything. Let me edit the hastebin.

**Comment by JBYoshi** [comment]
I'll take care of this.

**Comment by JBYoshi** [comment]
This just got a lot harder than I initially realized. When sending a resource pack to the client, the server can optionally provide a value called a hash, which is unique for each resource pack. In previous versions of Minecraft, when the client sent the status back to the server (which would call the `ResourcePackStatusEvent`), it would include the hash; I used that to identify the resource pack in the event. However, since Minecraft 1.10 (prerelease 1), the client no longer sends the hash back, so I can't identify the resource pack with it anymore.

I thought of using a `Queue` of sent `ResourcePacks`, where a status is bound with whatever is on the front of the queue, and the resource pack is popped off if the response is final (`SUCCESSULLY_LOADED`, `DECLINED`, or `FAILED`). However, it gets a bit wonky:

* If the user closes the resource pack request window with the Escape key, no status will be sent, and the original resource pack remains on the `Queue`. Then, if another resource pack request is sent and the user responds with a button, the client will send a status, and the event will be fired for the resource pack on the 
* If one resource pack request comes in while the prompt is still up for another, the original window will close as if the Escape key had been pressed (see above) and the new window will open. This would cause the same conflict as above.
* If one resource pack request comes in while another is being downloaded, two `ACCEPTED` statuses could come in in a row, then two `SUCCESSFULLY_LOADED` statuses. The second `ACCEPTED` status should be bound to the second `ResourcePack`, but the first is still on the front of the queue, so it's bound to the first. In addition, whichever pack finishes downloading first gets the event fired first, so the first `SUCCESSFULLY_LOADED` status could be bound to the second `ResourcePack` sent.

Not sure how to do this anymore...

**Comment by kashike** [comment]
@JBYoshi The hash was removed from the serverbound resource pack response packet since it isn't officially needed.
Best thing would be to just remove the list/queue/etc that we have now and just wait for a response packet.

**Comment by Cybermaxke** [comment]
You can also resend the resource pack packet until they actually click the yes or no button. And queue the resource packs to wait for a response before sending the next one.

**Comment by JBYoshi** [comment]
I'm working on a similar idea to what @Cybermaxke suggested.

* All resource pack requests are stored in a queue. If a request is made when the queue is empty, it is sent to the client and added to the queue. If a request is made when the queue isn't empty, it's only queued.
* If the player hits Escape, the resource pack request won't immediately pop back up. However, if the player does something (specifically, anything that would reset the AFK timer), the server knows that the user must have closed the menu, and it resends it. (This is to make sure that if this behavior is changed in the future, there won't be any issues.)
* When a request is fulfilled (I call a resource pack request "fulfilled" when the client sends a `REJECTED`, `ERRORED`, or `SUCCESSFULLY_LOADED` status), it is popped off the queue. If there is exactly one more request on the queue, that request is sent to the client.
* If a request is fulfilled and popped off the queue, and two or more requests remain, only the last one will be sent to the client. The other ones are removed from the queue, and events are fired for them, in order, based off of the result of the first request, although I'm not quite sure what events should be fired in what case.

**Comment by chasem-dev** [comment]
I was wondering if this could be added to 1.10! 

Also, would it be possible to add a way to prompt/send the player the resourcepack on our own terms? Say from a command or some sort of NPC.

Tried something along the lines of             
player.sendResourcePack(Sponge.getServer().getDefaultResourcePack().get());

**Comment by JBYoshi** [comment]
The default resource pack is automatically sent when the player joins. You can't change that behavior. However, you can remove it from `server.properties` and create and send your own.
