### ISSUE TITLE
BlockChangeEvent.Post shouldn't be constantly fired.

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/Sponge#1072]
So after some conversations between blood and myself, the Post event was added to block change events.

Post was originally meant as a solution to bulk block events that don't consist entirely of place, break, modify, grow, and decay transactions. This special Post event would fire for odd things like pistons and daylight sensors.

Now, Post fires for ALL events, even if they are not hybrid events. This mean that EVERY block change causes TWO events to be fired, with the exception of hybrid changes, which I believe still only fire Post.

This was originally a bug when changing API versions, but it was allowed to stay as part of an impromptu design decision.

One argument for keeping this change is that a Post event would allow block logging plugins to listen to just one event. However my counter argument is that you could have originally just listened to the generic BlockChangeEvent without any issues. There is no need to have an additional Post event for this purpose. 

The point of Post is to make things like pistons a little easier to deal with, but with the changed behavior, it's just potentially a cause for bad performance, and an unnecessary event.

I'm going to leave this issue here. Input is very welcome.

**Comment by gabizou** [comment]
> Post was originally meant as a solution to bulk block events that don't consist entirely of place, break, modify, grow, and decay transactions. This special Post event would fire for odd things like pistons and daylight sensors.

Post was originally designed as a multi event, where two separate `ChangeBlockEvent`s could be fired (`Break`, and `Place`) and then a third event containing the multiple events would be fired thereafter. 



> Now, Post fires for ALL events, even if they are not hybrid events. This mean that EVERY block change causes TWO events to be fired, with the exception of hybrid changes, which I believe still only fire Post.

Depends on the circumstance, if you take the circumstance of placing a block and breaking other blocks, the post would technically be the third event. In the logic of how they're processed, Post is always going to include the changes made by plugins of the previous two events.



> One argument for keeping this change is that a Post event would allow block logging plugins to listen to just one event. However my counter argument is that you could have originally just listened to the generic BlockChangeEvent without any issues. There is no need to have an additional Post event for this purpose.

You would still need to filter out `ChangeBlockEvent.Post`, never could you just listen to `ChangeBlockEvent` and not get a `Post` event accidentally when you least expected it. The problem ended up being that you wouldn't know whether there IS going to be a `Post` event from just a `Break` event or a `Place` event, since the `Post` is fired, well, afterwards.



> The point of Post is to make things like pistons a little easier to deal with, but with the changed behavior, it's just potentially a cause for bad performance, and an unnecessary event.

Could you back up the performance claim with some numbers?
