### ISSUE TITLE
Human entities don't seem to be saved to disk

### ISSUE THREAD

**Issue by windy1** [SpongePowered/Sponge#1074]
Human entities do not persist across server restarts (tested on 1.10.2 / SpongeVanilla 5.1.0)

**Comment by windy1** [comment]
Update:

Tested on 1.11 now, entity seems to be saved to disk, but is not loaded (or not loaded properly) on start.

**Comment by me4502** [comment]
Related to https://github.com/SpongePowered/SpongeCommon/issues/1047

**Comment by windy1** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/73ce67dcc44213c936eeeb4b30d2825a419f7b8e

Gonna work on a few other fixes before this gets merged. Will also require an API change because `Human` must extend `Living` and not `Creature` because of `DataParameter` ID collisions. @gabizou 

This was causing an expected byte data param to actually be a float. Specifically `AI_FLAGS`.

**Comment by simon816** [comment]
@windy1 `EntityHuman` should extend at least `EntityLiving` in order to attach AI, handle armor inventory and a few other things.

What seems to be the case is that it's using DataParameters from EntityPlayer and merging them with parameters in EntityLiving.
From what I can tell, DataParameters are supposed to be private instances for a particular entity. I think all that needs to happen is to define the parameters locally in EntityHuman.
The use of parameters from EntityPlayer is incorrect usage, obviously not realised at the time when mojang refactored the data watcher system.

**Comment by windy1** [comment]
@simon816 Yes that's exactly what's happening and you might be on to something there. Are the player parameters even used elsewhere? Are they necessary at all even?

**Comment by simon816** [comment]
OK So I just realised a slight problem with the attributes. Using private instances of the parameters will still cause issues.
Index 11 now overlaps from ['Player'](http://wiki.vg/Entities#Player) and ['Insentient'](http://wiki.vg/Entities#Insentient)
On the client, it spawns an `EntityOtherPlayerMP` therefore the client expects all attributes from Player to exist at the indexes listed on http://wiki.vg/Entities#Player

Because EntityHuman extends ['Insentient'](http://wiki.vg/Entities#Insentient) (via ['Creature'](http://wiki.vg/Entities#Creature)), the index 11 differs from client to server.
What I suggest we do is override any traces of `AI_FLAGS` on `EntityHuman` since the client doesn't expect that attribute.
Note how on 1.8 [No attributes overlapped](http://wiki.vg/index.php?title=Entities&oldid=7415#Human)

**Comment by windy1** [comment]
@simon816 The lack of AI_FLAGS being registered was the cause of the initial issue when the entity was being written to NBT and `EntityLiving` expects it to write the handedness property. I believe it's critical in other places on the server as well for `EntityLiving`.

**Comment by joeyasselin** [comment]
@windy1 I'm noticing this issue too, but no error like me4502 mentioned above. Is this issue fixed in the fix/humans branch or is there more to do?

**Comment by JBYoshi** [comment]
Can this be closed?

**Comment by windy1** [comment]
No

**Comment by JBYoshi** [comment]
I thought @Zidane said in SoS that he fixed this?

**Comment by windy1** [comment]
My mistake, hadn't realized.
