### ISSUE TITLE
Containers not dropping the correct quantity of items

### ISSUE THREAD

**Issue by vectrixdevelops** [SpongePowered/Sponge#1079]
Referring to this post, https://forums.spongepowered.org/t/chest-item-drop-bug/16224

When destroying a chest with items inside sometimes it does not drop the full stack and sometimes even nothing at all.

@gabizou (gravityfox wanted a tag for you)

EDIT: Happens to furnaces too.

SpongeVanilla-1.11-6.0.0-BETA-187

**Comment by ziceptor** [comment]
I confirm that I have the same error.

forge-1.11-13.19.1.2195-universal.jar
spongeforge-1.11-2195-6.0.0-BETA-2001.jar

**Comment by vectrixdevelops** [comment]
Got an error for this. https://gist.github.com/connorhartley/68c6756b2e39d72571bfe626a0e556f5

**Comment by ziceptor** [comment]
This happens with furnaces, dispensers, etc.

forge-1.11-13.19.1.2195-universal.jar
spongeforge-1.11-2195-6.0.0-BETA-2004.jar

**Comment by ziceptor** [comment]
http://pastebin.com/xuwXDyae

**Comment by Zerthick** [comment]
I can confirm this also occurs for chests on spongevanilla-1.10.2-5.1.0-BETA-366

**Comment by Faithcaio** [comment]
Not quite sure how to solve it yet, but this is what I could figure out:

A registered `DropItemEvent.Destruct` Listener will get called twice.

After breaking the chest the entities are created and added to a list to pass onto events etc.

The error happens in the if block starting at `PacketFunction:432` (`state == INTERACTION`)
First the items are spawned at:
`PacketFunction:435` -> `TrackingUtil.processBlockCaptures` -> `performBlockAdditions` -> `spawnEntitiesForBlockDrops`
and then a second time at:
`PacketFunction:564` -> `processSpawnedEntities` -> `processEntities`

Bug was probably introduced with 848f545

**Comment by XakepSDK** [comment]
spongeforge-1.11.2-2201-6.0.0-BETA-2018.jar
forge-1.11.2-13.20.0.2201-universal.jar
has same error.

**Comment by parlough** [comment]
I thought this was caused by my plugin originally, but when I saw this issue and I got more reports I tested it further and it seems to occur to all containers. You will rarely, if ever, see the original amount of the item drop. Generally a random amount of the original stack is dropped or nothing at all, there is no rhyme or reason to it.

Here is a small video if it occurring with a chest and furnace with the latest SpongeVanilla build(Sorry for the loud volume, turn down or mute the video): https://www.youtube.com/watch?v=RHS9rxLYDVk

I am not really sure how to approach the issue but if anyone needs help testing solutions feel free to get in contact.
