### ISSUE TITLE
ClientConnectionEvent.Login not fired when banned user tries to join

### ISSUE THREAD

**Issue by codeHusky** [SpongePowered/Sponge#1093]
For some reason, and I'm not quite sure exactly why, Login is not fired when a banned user attempts to join.
```
@Listener
public void onDisconnect(ClientConnectionEvent.Login event){
    logger.info("hey.");
}
```

**Comment by simon816** [comment]
Try `ClientConnectionEvent.Auth`. I think the ban check happens there

**Comment by Aaron1011** [comment]
If the player is banned, the event will [be automatically cancelled](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/event/network/ClientConnectionEvent.java#L95-L102), which means that you'll need to use `@IsCancalled(Tristate.UNDEFINED)`

However, this behavior isn't very intuitive, so I'm thinking of changing it to pass in some kind log 'LoginCause'.

**Comment by gabizou** [comment]
I'd say this is intended, since causes already serve and event filters already serve. We don't want to have plugins unintentionally setting up data for already banned players, and since the ban service already says the player is banned, it makes sense that the event is "pre-cancelled". 

Seeing as it's almost been two years since the issue was opened but no advancements have been made, I'm electing to keep with the original implementation design and leave the documentation as is.
