### ISSUE TITLE
The specified mapping 'snapshot_20161129' does not exist!

### ISSUE THREAD

**Issue by Favorlock** [SpongePowered/Sponge#1106]
Attempting to clone the repo and setup the workspace, however, I'm getting the error specified in the title. I've followed the steps as shown in the readme. Any ideas why I'm getting this error?

**Comment by stephan-gh** [comment]
Unfortunately, the server hosting the MCP mappings is down currently (http://export.mcpbot.bspk.rs). You will need to wait until it's back up.

**Comment by char** [comment]
Raises an issue concerning single-points-of-failure, really. (But that's out of scope for a SpongeCommon issue.)

**Comment by gabizou** [comment]
> Raises an issue concerning single-points-of-failure, really.

To be honest, the mappings repository being down would affect far more than just sponge at this point, since it's the backbone for forge modding and other modding development communities. That being said, it's the [internet, sometimes things go down.](https://www.cnet.com/news/google-goes-down-for-5-minutes-internet-traffic-drops-40/)
