### ISSUE TITLE
Velocity 0 to launch projectile

### ISSUE THREAD

**Issue by TheSebakl** [SpongePowered/Sponge#1114]
When i do player.launchProjectile it doesn't give velocity
the problem come from modulo system i think

**Comment by JBYoshi** [comment]
What projectile are you trying to launch? Sponge has different behavior for each type.

**Comment by TheSebakl** [comment]
i tried to launch a snowball, i do player.launchProjectile(Snowball.class) 
(i don"t have my codes open here)
and the snowball spawn at player and fall like a sh*t

**Comment by simon816** [comment]
I have confirmed this issue. It appears that Mojang changed the `EntityThowable` constructor and moved some velocity handling logic into a new method that needs to be called by the calling party.
Since sponge's projectile launcher hasn't been updated to reflect these changes the velocity isn't getting set.
