### ISSUE TITLE
TextTemplate and Text.Builder inconsistency

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Sponge#1152]
```java
Text clickText = Text.of(TextActions.suggestCommand("Clicked!"), "[Click]");
Text noClickText = Text.of("[NoClick]");

Text t1 = Text.of(clickText, noClickText); // right behavior
Text t2 = Text.builder().append(clickText).append(noClickText).build(); // right behavior
Text t3 = TextTemplate.of(clickText, noClickText).apply().build(); // wrong behavior
```

`t1` and `t2` are right: The `[Click]` part can be clicked and the `[NoClick]` part not.
In `t3` the `[Click]` and `[NoClick]` part can be clicked.

Is this intended or am I using it in a wrong way?

<sub>I hope this is correctly placed in SpongeCommon</sub>

Edit: I found a workaround:
`Text clickText = Text.of(`__Text.of()__`, TextActions.suggestCommand("Clicked!"), "[Click]");`

Also I found out that when combining multiple TextActions and normal Texts that the first Text's action defines the behavior for the Texts that don't have an action. In this case `Text.of()` doesn't have an action and so `[NoClick]` doesn't get the action from `[Click]`.

2nd edit: This behavior applies to the whole formatting to. So coloring the first text in a template results in like setting the default coloring of the whole template, where no color is set the first one is used.

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 7) of SpongeAPI. Support for API 7 ended in January 2022.

API-7 is now end-of-life. We will not be issuing any more API updates for version 7 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API7/1.12.2[^2]
___

The Text API is now supplied by the [Kyori Adventure library](https://github.com/KyoriPowered/adventure/) so this issue is no longer relevant to this repository.

[^1]: https://forums.spongepowered.org/t/status-update-8th-january-2022-spongeapi-8-released/39861#minecraft-1122-spongeapi-7-10
[^2]: https://forums.spongepowered.org/t/sponge-status-update-28th-may-2022/40135#api-71122-community-support-8
