### ISSUE TITLE
Getting BiomeType from id does not work with minecraft: prefix

### ISSUE THREAD

**Issue by JonathanBrouwer** [SpongePowered/Sponge#1217]
Getting a BiomeType from id using the following code returns Optional#empty
Sponge.getRegistry().getType(CatalogTypes.BIOME_TYPE, "minecraft:mesa");

While this returns a result
Sponge.getRegistry().getType(CatalogTypes.BIOME_TYPE, "mesa");

Using minecraft:mesa should world considering the BiomeType#getId() does return the correct id with the minecraft: prefix.

**Second issue:**
Some biome types don't actually seem to be gettable at all, for example the 'mutated_plains' (all mutated biomes, what even are mutated biomes?). Trying to get them just results in a Optional#empty

**Comment by Deamon5550** [comment]
The mutated plains biome is actually called `sunflower_plains` I'm guessing the ids are broken. I'll look into all of these.

**Comment by kashike** [comment]
@Deamon5550 No it isn't, it is `mutated_plains`.
```
        registerBiome(0, "ocean", ...
        registerBiome(1, "plains", ...
        registerBiome(2, "desert",...
        registerBiome(14, "mushroom_island", ...
        registerBiome(36, "savanna_rock", ...
        registerBiome(37, "mesa", ...
        registerBiome(38, "mesa_rock", ...
        registerBiome(39, "mesa_clear_rock", ...
        registerBiome(127, "void", ...
        registerBiome(129, "mutated_plains", ...
        registerBiome(130, "mutated_desert", ...
        registerBiome(131, "mutated_extreme_hills", ...
        registerBiome(132, "mutated_forest", ...
```

**Comment by Deamon5550** [comment]
@kashike [in our registry](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/registry/type/world/gen/BiomeTypeRegistryModule.java#L113) it's `sunflower_plains` because I wrote that before biomes had string ids in the base game. The fact that you can't get it as mutated_plains is a separate issue:
        
- getById needs to append minecraft: if no namespace is given
- registerDefaults should just loop the registry
- biomes whose ids differ between sponge and mc should be registered seperately
- biome mappings should be updated if a mod changes them, right now they are ignored
- registerDefaults should register ids with the minecraft: namespace
- mutated biome ids are broken
- also looks like we're missing the mutated biomes in BiomeTypes

**Comment by kashike** [comment]
Ah, so our registry just needs to be updated to match, then - alright. I thought you were referring to the real ids.

**Comment by Deamon5550** [comment]
this was done in 9d594880e16905f61784f37d0bc890da05981caf
