### ISSUE TITLE
User implementation requires discussion

### ISSUE THREAD

**Issue by caseif** [SpongePowered/Sponge#122]
I made an attempt today to implement the `User` interface and quickly realized that Minecraft has no comparable concept, and that the differences between Sponge and vanilla Minecraft's inheritance tree make it somewhat difficult to find an appropriate place to do so.

Most of the methods from `User` can theoretically be implemented within Minecraft's `EntityPlayer` class; however, `EntityPlayer` is comparable to Sponge's `Human`, which, being a superclass of `User`, makes this solution unfeasible. Likewise, while it could also be implemented in Minecraft's `EntityPlayerMP` (comparable to Sponge's Player), not all `Users` are necessarily `Player` entities, and the methods would remain unimplemented for such cases.

Currently, I'm unsure of how to proceed, and would appreciate input on the matter.

**Comment by simon816** [comment]
There's no need to use a mixin for `User`.

Instead, `User` can be a wrapper style class, say `SpongeUser`. See [`BlockWrapper`](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/wrapper/BlockWrapper.java) for example.
The class `SpongeUser` will hold a reference to the user's GameProfile and access things from the server instance like whitelist, player data directory (for accessing inventory data) etc.

**Comment by mproncace** [comment]
@Deamon5550 @simon816 The issue with both of these solutions is that the User implementation would then be removed from the normal entity hierarchy. They're both doable, but wouldn't function properly without special measures that are beyond me

**Comment by Zidane** [comment]
@Minecrell 

You may want to comment here due to your API changes with GameProfile.

**Comment by Minecrell** [comment]
I don't think we can use a mixin for `User`. `authlib.GameProfile` is not a good target for that because we added `sponge.GameProfile` to the API recently and it implements that already. Even without, `GameProfile` represents a different level, an identification and a few properties of players without any persistence.

Because of that we will most likely need to create an extra class for `User`. I don't think you can call it a wrapper class, because there is no real underlying class for this in Minecraft. Instances of this class would be created only when they're needed by a plugin.

@caseif I don't think an `User`, in general, should be an entity. It's neither existent in the world nor actually any living entity. Although you could possibly implement most of the entity methods by just modifying the saved data, but it would still not apply to the correct definition of entities in the SpongeAPI.

**Comment by simon816** [comment]
@modwizcode I agree, so it would be `player.getUser().isBanned()` for example. (Or maybe `getData`)

It may be useful to see some old comments on the use of an offline player, https://github.com/SpongePowered/SpongeAPI/pull/72#issuecomment-61722438
Before `OfflinePlayer`  was renamed to `User`, I made a [comment](https://github.com/SpongePowered/SpongeAPI/pull/217#discussion_r20640425) that Player is not a type of OfflinePlayer.
There seems to be a missing method in the API to access offline players, you cannot get user data without them being online when retrieving it. I think `Server#getUser(UUID)` should be added.

**Comment by Mumfrey** [comment]
@modwizcode I have to agree with that as well, it seems like the most logical relationship. However there's no reason that `Player` can't still *implement* `User` and simply proxy all the method calls to the internal `User` instance for convenience purposes.

**Comment by simon816** [comment]
I have a PR open, SpongePowered/SpongeCommon#87
Any further discussion can happen there.

**Comment by gabizou** [comment]
@simon816 Don't close the issue until it has been resolved.
