### ISSUE TITLE
Concurrency issues with async lighting

### ISSUE THREAD

**Issue by Deamon5550** [SpongePowered/Sponge#1234]
Recently a feature was added to [update lighting asynchronously](https://github.com/SpongePowered/SpongeCommon/commit/9997dca424377e08bc8468bd95a502353b4e4667). Great in theory however there is a problem with the current implementation. It relates to the Long2ObjectOpenHashMap that the chunks are stored in and is made worse by the `CachedLong2ObjectOpenHashMap` that we have, although removing the cached map would not fix the issue. The problem is that the chunk map is not thread safe and calls are made from outside the main thread to get chunks from the map. Especially with the cached map this creates a race condition if two threads try and get a chunk at the same time one of the threads can end up with the wrong chunk!

A possible fix would be to setup the data needed to do the lighting calculations on the main thread and package it into a task that is then passed off to a worker thread for the actual calculations. It should be possible to engineer to require no accessing of chunks or other non-thread safe data structures from outside the main thread. I would not consider replacing the collection with a thread safe variant to be a solution nor would using mutexs help, as the end result would likely be an overall slowdown of the game even when lighting is not in the process of being calculated.

**Comment by ladehaug** [comment]
I'm currently stuck at build 2169 because monster spawners are not behaving correctly. I'm running a server with doomlike dungeons installed. When using build 2172 or later the spawners are almost not spawning any mobs at all, even when they are placed in pitch dark. The same issue can be seen in ordinary dungeons generated by vanilla minecraft as well. This surely needs to be fixed.

--
Geir
