### ISSUE TITLE
Duplicate Block ChangeBlockEvent cancelled

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/Sponge#1251]
Hi,
when I cancelled event "ChangeBlockEvent" on gravity block. The block is duplicated
Event SpawnEntityEvent is launched before ChangeBlockEvent.

Example Gravity Block : [Sand](https://www.youtube.com/watch?v=7-Tj5ZfsJDs&feature=youtu.be) 
Example No Gravity Block : [Rail & Cactus](https://www.youtube.com/watch?v=41hv5wo_2D8)

Version : SpongeVanilla-1.11.2-6.0.0-BETA-231

**Comment by ryantheleach** [comment]
This seems to be much worse in SpongeVanilla (379).

It's stuck but repeating, creating a whole column of sand.

**Comment by JBYoshi** [comment]
Steps to reproduce:

1. Add this code in a plugin:
```java
    @Listener
    public void dupe(ChangeBlockEvent e) {
        if (e.getTransactions().stream().anyMatch(t -> t.getOriginal().getState().getType().equals(BlockTypes.SAND))) {
            e.setCancelled(true);
        }
    }
```
2. Place a block of stone in the air.
3. Place a block of sand on top of the stone block.
4. Break the stone block.

**Comment by JBYoshi** [comment]
I think the problem is that `BlockTickPhaseState` doesn't capture entity spawns.

**Comment by gabizou** [comment]
So, worked on narrowing down on this issue, from what I'm understanding of the implementation (vanilla and our own):
1) Place a sand block on another block
 - At this point, everything is working out.
2) Break block beneath sand
 - Due to a neighbor update (which is listenable through an event listener for the neighbor notification), the sand block is going to be ticked the next tick
3) The Falling entity is spawned by the next tick on the block, which does make sense that @JBYoshi's statement that it does not get an entity spawn event call
4) Cancelling the block removal after the entity is spawned and ticked, the block itself is still scheduled to be ticked and therefor will continue to spawn entities until it can no longer fall

What I'm going to suggest isn't so much of a "fix" since the plugin developer would have to know that they have to cancel the Spawn of the falling entity, and maybe even as a precaution, cancel the notification of the fallible block. Ultimately, right now, we'd have to heavily modify the entity falling block logic to consider that if the block change event is cancelled *in the instant it attempts to remove the original block* to remove the falling block.

**Comment by gabizou** [comment]
Yeah, so far, the "test" allows for the block to stay there, but cancelling the entity spawn is more than likely the better "fix". 

I went and added an implementation change for it on Sponge's side, but the block will still flicker with the entity being spawned.

All in all, I think due to the implementation of Minecraft, what Sponge will do is the best it can do, and ultimately, plugins will have to cancel the falling block spawns (though I'll add in a specialized spawn event for it so the cause stack can be utilized nicely).
 

Update: Further looking into it: There's already a [SpawnType](https://github.com/SpongePowered/SpongeAPI/blob/8b23bcf54cb6e91d5edf1829d48a65f1043aeec9/src/main/java/org/spongepowered/api/event/cause/entity/spawn/SpawnTypes.java#L95) to use for this.

I'll allow cancelling the event to kill the entity, but I'll still stand by that the spawn entity event needs to be cancelled instead.
