### ISSUE TITLE
Frozen chunk on map generated by Minecraft with Sponge API

### ISSUE THREAD

**Issue by therealmikz** [SpongePowered/Sponge#1285]
Previously https://github.com/SpongePowered/SpongeAPI/issues/1530

Originally I wrote about it on Sponge forum, here's the link: https://forums.spongepowered.org/t/sponge-alters-world-generation-bug-or-feature/18325/4

Yesterday I tried to run a new Sponge-based server based on version 1.10.2 (using sponge-forge 1.10.2-2254-5.2.0-BETA-2264). Everything worked except one tiny detail. On the world that I generated using seed that was provided by hand (5643637565697398741), I stepped on a single chunk that couldn't be altered in any way - I was unable to destroy or place blocks on it.
So I started to look what's wrong. Recreating the world didn't fix it, Changing version from forge to sponge vanilla (1.10.2-5.2.0-BETA-385) also didn't help, so the problem wasn't forge.
After all I decided to try to run a server using vanilla Minecraft (the jar file that was automatically downloaded by sponge vanilla), and there was a surprise waiting for me: not only mentioned chunk was no longer frozen, but it also looked entirely different (there were dirt/grass blocks instead of stone). Just by a glimpse I could clearly tell the differences between the world generated by Sponge version and the one that was created by vanilla Minecraft. It's visible that generated terrain is similar in both versions, but blocks are clearly different. Screenshots are attached in the forum topic that I linked to, but that's not the case since this issue is about frozen chunks.

Conclusion: frozen chunks shouldn't be there, so this clearly is a bug.

Some information:

Minecraft version: 1.10.2
Sponge Forge version: 1.10.2-2254-5.2.0-BETA-2264
Sponge Vanilla version: 1.10.2-5.2.0-BETA-385
Also occurs on: Sponge 1.11.2 and 1.8.9
World seed: 5643637565697398741
Frozen chunk position: -31 +220
Platform: Dockerized Debian 8 with java 8 (OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14) OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode) ), host system: Ubuntu Server 16.10
Also tested on platform: Windows 8.1 with Oracle Java 8, with same effects

World regeneration steps:

Run server
Stop server after configuration and world initialization
Remove "world" directory
Provide level seed in server.properties
Start server and wait for world regeneration

**Comment by therealmikz** [comment]
Ah, I didn't make it clear: position of chunk that I mentioned in this ticket is in fact block coordinates.

**Comment by ryantheleach** [comment]
@therealmikz I checked this out in singleplayer, dev environment, I was not able to reproduce.

I suspect what you are seeing (due to it's relative closeness to the spawn point) is the natural vanilla spawn protection. http://minecraft.gamepedia.com/Server.properties under spawn-protection

In vanilla the OP status normally bypasses this protection, but in Sponge it is remapped to a permission for greater flexibility.

Ensure that you have the permission minecraft.spawn-protection.override , or that the spawn protection radius is set to 0 to disable this behavior.

You can check the other permissions that sponge adds here: https://docs.spongepowered.org/stable/en/server/spongineer/commands.html

It was rather awkwardly placed under commands, but that's where the rest of the permissions are.

**Comment by therealmikz** [comment]
You are right, it was indeed spawn protection, setting radius to 0 did it, thank you very much for such comprehensive answer! I'm closing this issue, there's nothing to be fixed here :).
