### ISSUE TITLE
Limit size of phase-exception stacktraces

### ISSUE THREAD

**Issue by TBlueF** [SpongePowered/Sponge#1301]
I've somehow got a phase-error that creates a 12MB big log-dump. I cant really tell you what caused the issue itself, because i could not reproduce it yet, but i want to suggest to somehow limit the size of those exception-dumps.. Because 70000+ lines are a little bit too much :D

You can find the example dump [here](https://craftednature.de/paste/2017-04-13-2.log.txt).

**Comment by gabizou** [comment]
Unfortunately, I don't believe that phase exceptions should be trimmed in any manner of speaking, but what the issue that you're not seeing is something of a bigger bug, since you have the server essentially being unable to complete a phase, constantly... It doesn't help that it looks like a place block packet is failing to exit successfully. IF possible, find the first stack trace and we can resolve the issue. Otherwise, there isn't much to "rate limit" for a phase stack exception, especially since in this case, it's running away (usually you want to try to catch it the first time, and not just let them continue stacking up like this).

**Comment by TBlueF** [comment]
*"IF possible, find the first stack trace"*
What do you mean? So an error like this can be caused by other ones that occurred an hour earlier? I included the [whole log](https://craftednature.de/paste/2017-04-13-2.log.txt) now .. there are two more errors at [12:43:39]..

*"usually you want to try to catch it the first time, and not just let them continue stacking up like this"*
Wait.. Just to make sure: Do you think this could be the fault of my plugin, or is it Sponge? I have to admit i haven't fully understood the cause-tracker and those phases yet ^^'

**Comment by phit** [comment]
>Now it will properly silence itself after one instance of an error of a particular kind, unless verbose is enabled.

added in https://github.com/SpongePowered/SpongeCommon/commit/bc80b91c722a57d1bc1e74a2a856db2f5af6684f by setting `verbose-errors=false` in the global.conf
