### ISSUE TITLE
Some questions about the project...

### ISSUE THREAD

**Issue by Yuri6037** [SpongePowered/Sponge#132]
Hello,

I was a big user of MCPC+ and Cauldron servers witch are now down due to the famous big DMCA takedown !

I just want to know two things :
- Will this software be able to run old CraftBukkit plugins ?
- Will this software be able to run Minecraft Forge server so i can install about 50 Mods like i was making on Cauldron ?

**Comment by jk-5** [comment]
All answers to these questions are on the sponge site, in the readme (https://docs.google.com/document/d/1VJ1WzHI-VUuoHEJz4SRHUbl-5XnsURbqP5fIi8B4Kyg/edit)

The software will not be able to run Bukkit plugins, but people in the community already said they were going to make a wrapper between the old Bukkit api and the new Sponge api

Sponge is written as a forge mod, so that means it needs MinecraftForge to run. You will be able to run other minecraft forge mods together with this.

Next time, search on the site or ask on IRC for these kind of questions ;)
