### ISSUE TITLE
When giving Levels directly (with /xp <level>L) player.get(Keys.TOTAL_EXPERIENCE) isn't updated

### ISSUE THREAD

**Issue by BrainStone** [SpongePowered/Sponge#1322]
When players recieve levels directly via the `/xp <level>L [player]` command the value of `player.get(Keys.TOTAL_EXPERIENCE)` remains unchanged. However the value is correct when reciving XP orbs or using the `/xp <experience> [player]` command.

**I am currently running...**

- SpongeVanilla version: 1.11.2-6.0.0-BETA-253, 1.11.2-6.0.0-BETA-252 and 1.11.2-6.0.0-BETA-243
- Java version: 1.8.0_121
- Operating System:

 - [x] Linux (Debian)
 - [ ] macOS
 - [x] Windows

**What is the expected result?**
That the value of total experience is increased when giving levels directly.

**What is the current result?**
The value remains unchanged.

See also: SpongePowered/SpongeVanilla#312

**Comment by BrainStone** [comment]
Also I noticed that when enchanting or repairing the value doesn't decrease.

**Comment by ryantheleach** [comment]
Does receiving experience by an orb, after gaining it with the command, give you the correct total?

**Comment by BrainStone** [comment]
@ryantheleach no it does not.

**Comment by stephan-gh** [comment]
When I tried to reproduce @BrainStone's bug report on SpongeVanilla I noticed that the total experience and the experience levels are tracked separately (and also saved separately) in the internal Minecraft server. I'm not entirely sure in which cases it converts between these values (I haven't checked yet).

**Comment by BrainStone** [comment]
Any updates so far?

**Comment by dualspiral** [comment]
I know what the issue is, I'm just unsure as to whether something should be done about it, and if so, whether it should be optional, because it's fundamentally a Vanilla issue - if indeed, it is an issue (and I'll explain my thinking in a moment).

The problem is, as stated, that the Minecraft server tracks total experience and levels (and the current fraction of experience between two levels) separately. When changing a player's total experience via the `/xp` command, Minecraft also ensures that the experience levels are updated. However, this does not happen the other way around, if the _levels_ are updated, the xp is _not_. This doesn't just happen using the `/xp` command, you also observe this behaviour when you repair an item using an anvil and enchant an item using the enchantment table.

The issue is that the method on the `EntityPlayer` that adds to the total experience also does the calculations to work out the level change, but directly calling the level change does not change the experience, _unless_ the level is set to zero. I see no other synchronisation points. It _could_ be that this is intentional, because the XP can the become some sort of score, whilst the levels are expendable - and a lower level will still allow you to benefit from a lower level interval. However, given that a zero level returns you to zero experience, this seems unlikely.

The fix I have would be to ensure that, when levels are changed outside of the method that adds experience points, is to check to see if there is a mismatch between the current experience and the current level, and, if so, recalculate the total experience (using the current percentage to the next level as a guide). To be clear, I have this ready to go - but I don't know whether this patch should be in an _optional_ mixin.

**Comment by parlough** [comment]
@dualspiral I don't see a point of it being optional. When would there be a need to control them separately. It just causes confusion for you as a plugin developer but also other plugins manipulating experience. 

Having it as an optional mixin makes plugin developers not know what functionality to expect and is harder to develop for.

If Minecraft has these insurances we should too. 

I think this would be a great addition, just not optionally :)
