### ISSUE TITLE
Error : DropItemEvent.Pre

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/Sponge#1363]
- SpongeVanilla version: 1.11.2 BETA 269
- Java version: 8 Update 131
- Operating System:

 - [x] Linux (Debian)
 - [ ] macOS
 - [x] Windows

When I remove all items in the list to event "DropItemEvent.Pre", I have this error [List Empty](https://pastebin.com/tMsUWZeH).
When I cancel event "DropItemEvent.Pre", I have this error [Cancel](https://pastebin.com/XyRPeBPj)

**Comment by rexbut** [comment]
The bug is also present in SpongeVanilla 1.12.1-7.0.0-BETA-319

**Comment by ImMorpheus** [comment]
The first one is fixed and a duplicate of https://github.com/SpongePowered/SpongeCommon/issues/1280 
I'm not able to reproduce the second issue on latest (bleeding branch) (probably fixed by JBYoshi's commit)

**Comment by ryantheleach** [comment]
@lesbleu Thanks for the report.

@ImMorpheus Thanks for testing this, I'm pretty confident that if you arn't able to reproduce it's fixed given the amount of worked touched here since august.

@lesbleu @rexbut If either of you are able to reproduce, feel free to comment to reopen or make a new issue.
