### ISSUE TITLE
Can't use any data manipulators in recipes

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/Sponge#1455]
**I am currently running...**

- SpongeForge version: 1.12-2397-7.0.0-BETA-2474:dev
- Forge version: 2397
- Java version: 1.8.0_131
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: No mods, only these lines which are called during PreInit:

```java
		reg.register(ShapelessCraftingRecipe.builder()
				.addIngredient(Ingredient.of(ItemTypes.SAND)).addIngredient(Ingredient.of(ItemTypes.REDSTONE))
				.result(ItemStack.builder().itemType(ItemTypes.SAND).add(Keys.SAND_TYPE, SandTypes.RED).build())
				.build("red_sand", this));
```

**What is the expected result?**
This craft: Normal sand + Redstone -> Red sand

**What is the current result?**
This craft: Normal sand + Redstone -> Normal sand

Recipe registration has to be done during PreInit while DataAPI become available during PostInit, so we can't use any data manipulators in recipes.

**Comment by theboomer** [comment]
Observations that may be totally meaningless overall, but...

This may be due to implimentation differences...  I just tested this code:
```
        Sponge.getRegistry().getCraftingRecipeRegistry().register(ShapelessCraftingRecipe.builder()                .addIngredient(Ingredient.of(ItemTypes.SAND)).addIngredient(Ingredient.of(ItemTypes.REDSTONE))
                .result(ItemStack.builder().itemType(ItemTypes.SAND).add(Keys.SAND_TYPE, SandTypes.RED).build())
                .build("red_sand", this));
```
in both (separately) the **GamePreInitializationEvent** and **GamePostInitializationEvent**, with SpongeVanilla-1.12Beta300, and **neither usage** is giving any result when mixing sand and redstone (ie, no normal sand craft result).

I tested this because of your comment about needing to be preinit, because I have been testing **smelting recipes,** and have been able to add the smelting recipes at the **GamePostInitEvent** with data -- display names, lore, stonedata types for ingredient, displaynames and dye data types for result.   The smelting gives the desired output for me, though it is not discriminatory on the lore/displayname of the input, but it does definitely show that the GamePostInit works for Smelting Recipes registration, it should be similar for other recipes no?

Unless spongeforge has different requirements for the registration than spongevanilla..?  The fact that I can't get your "result=normal sand" recipe to work either way in vanilla is a bothersome difference right now.

**Comment by theboomer** [comment]
SPV now supports the crafting recipes but limited to preinitialize event suffers the same data-manipulator missing results, unless the author here and myself are missing other ways from the available methods to force the datamanipulator to the result or input ingredients.

IE challenge recipes to make work are  this redsand recipe , and andesite crafted to a potato  -- to demonstrate specificity against parent sand/stone types :)
