### ISSUE TITLE
A simple way for forge mods to use some Sponge types.

### ISSUE THREAD

**Issue by AlphaModder** [SpongePowered/Sponge#146]
For things that directly correspond to a Minecraft object, there could be an interface not in the server API, but in the Forge implementation: "IMinecraftType<T>". It could look like this:

```java

public interface IMinecraftType<T>{
    public Optional<T> getMinecraftType();
}

```

This way, objects like, say DamageType could implement it, and behind the scenes the default ones could return the corresponding DamageSource, to allow for mod/plugin interop.

**Comment by Mumfrey** [comment]
They already do, a simple `instanceof` check is all that's needed :/

**Comment by AlphaModder** [comment]
@Mumfrey Oh, so we can literally make the Sponge types the same as Minecraft types with no proxy like CraftBukkit had? Cool then. Someone should delete this...

**Comment by Mumfrey** [comment]
For the most part (note, *most part*, there are some exceptions), the Sponge types are being applied directly to the Minecraft types using a system known as *Mixins* (literally, we "mix in" the Sponge code into the Minecraft code). This allows very efficient implementation of the API because unlike CraftBukkit where there were essentially *two* objects for every object, with Sponge there is only one.

Since we simply add our code and interfaces to the underlying objects, it means that all that's required to go back and forth between "Minecraft" objects and "Sponge" objects is a simple `instanceof` check and a typecast, because they are one and the same.
