### ISSUE TITLE
Semi-Urgently needed implemented methods (2 of them)

### ISSUE THREAD

**Issue by me4502** [SpongePowered/Sponge#150]
Two methods are needed semi-urgently (Within a day), for internal reasons.

See me on IRC for more details as to why.

SpongeMessage#of, and Entity#setLocationAndRotations

And more:
Message#toLegacy

Alongside this, the Tile Entity branch is needed, however that can just be obtained from that branch.

**Comment by simon816** [comment]
I had implemented `setLocationAndRotations` in [#141](https://github.com/SpongePowered/Sponge/pull/141/files#diff-d1e54a67a6e6054ffea2c372f361a87cR369) but don't know if it is completely correct

**Comment by me4502** [comment]
It doesn't appear to be, MC has a packet that allows for relative teleportations, it may need to be done a special way.

**Comment by Minecrell** [comment]
It wouldn't make a lot of sense to implement `SpongeMessage.of(IChatBaseComponent)` and `Message.toLegacy()` right now because I'm doing a few changes to the Text API in https://github.com/SpongePowered/SpongeAPI/tree/feature/text that will probably change a bit how this is going to be implemented. I'm planning to implement these methods in Sponge after I finish the improvements for the API.
