### ISSUE TITLE
Commands should fallback if no permission and conflicting aliases.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Sponge#1581]
```
02:30 | <sponge\|65427> | herro
02:31 | <sponge\|65427> | ./help doesnt seem to work on horizons 3 is this a sponge thing ??
02:32 | <sponge\|65427> | minecraft.command.help is already added
02:42 | <⇅K​e​a​t​o​n​> | Add this, sponge.command.help
```

At the moment if we override minecraft:help with Sponge commands, but you don't have permission to access the overridden command, you are not able to run the default Minecraft help.

Should this be by design? or should commands fallback if the user doesn't have permission?

**Comment by dualspiral** [comment]
This issue has been here a long time, and I'm going to close it especially with the advent of API 8.

> Should this be by design? or should commands fallback if the user doesn't have permission?

There's not much we can do. Only one command can be registered to an alias at any one time and it wouldn't really make sense to do otherwise. In general, a plugin will override a command for a reason - letting it fallback semi-defeats the purpose.

It's not really technically possible to do anyway. If there are three commands that tried for the same name, which do we go to, for example?

Let's keep it simple. Additionally, we've not included a help command in 1.16+ builds at the moment, and that probably won't change...
