### ISSUE TITLE
ChangeInventoryEvent.Pickup doesn't respect changes to its slot transactions

### ISSUE THREAD

**Issue by VapidLinus** [SpongePowered/Sponge#1597]
Altering the transactions of `ChangeInventoryEvent.Pickup` doesn't change anything.

Trying to invalidate a transaction doesn't work. Nothing happens and there are no errors or warnings. The player gets the dropped item like normal, whereas I expect them not to receive anything.
```java
@Listener
public void onItemPickup(ChangeInventoryEvent.Pickup event) {
	for (SlotTransaction transaction : event.getTransactions()) {
		transaction.setValid(false);
	}
}
```

Attempting to change a transaction doesn't do anything either. Nothing happens and you get the dropped item. Using this code I expect any affected slot's content to be replaced with a single dirt block.
```java
@Listener
public void onItemPickup(ChangeInventoryEvent.Pickup event) {
	for (SlotTransaction transaction : event.getTransactions()) {
		transaction.setCustom(ItemStack.of(ItemTypes.DIRT, 1));
	}
}
```

> spongevanilla-1.12.2-7.0.0-BETA-352.jar

**Comment by Faithcaio** [comment]
This is because Pickup is the only Inventory Event that fires BEFORE the change happened. 
The Slots passed in the event are fake ones that do not represent the actual inventory.
What I think needs to be done is to somehow split this event up in a Pre (actual pickup with Item Entities) and Post (Inventory Change after pickup happened) Event.

see https://github.com/SpongePowered/SpongeCommon/issues/1402

**Comment by Faithcaio** [comment]
should work with that merged PR
