### ISSUE TITLE
remainingJoinedStrings not completing player names when tab

### ISSUE THREAD

**Issue by FabioZumbi12** [SpongePowered/Sponge#1634]
**I am currently running...**

- SpongeForge version: spongeforge-1.12.2-2555-7.0.0-BETA-2757
- SpongeVanilla version: 
- Java version: 1.8
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 
Plugins (9): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, EconomyLite, LuckPerms, Nucleus, SignEditor, UltimateChat
**What is the expected result?**
Using `GenericArguments.remainingJoinedStrings` tab-complete the name of online players.
**What is the current result?**
Not tab completing for online player names.
[latest.log](https://github.com/SpongePowered/SpongeCommon/files/1524577/latest.log)

The code used to reproduce this: https://github.com/FabioZumbi12/UltimateChat/blob/master/UltimateChat-Sponge-56/src/main/java/br/net/fabiozumbi12/UltimateChat/Sponge/UCCommands.java#L331

**Comment by dualspiral** [comment]
[This is intentional](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/command/args/GenericArguments.java#L784-L797). In general, you don't want there to be tab completion for strings, integers, etc. That includes having player names - usually, if you're wanting to get a player out, you'd use `GenericArguments.player()` anyway.

That said, recognising this use case, I personally don't think I'd be _completely_ against Players auto completing in string parameters as long as it's added _as an option_ - I can add a modifier for SpongePowered/SpongeAPI#1587.

You may wish to create a wrapper `CommandElement` that overrides the suggestions only, performing this tab completion for you (or use the new API 7 method `withSuggestions`).

Related, from Discord, killjoy said:

> The issue is that if the suggestions come back empty, it should populate it with online players.

Not necessarily. There are many legitimate times where tabbing should not produce a result - integers, for example. Tabbing a player name there does not make sense. Same if an invalid input is being entered for choices, if you put in a string that doesn't match anything and then tab, a `Player` is not an appropriate choice.

**Comment by FabioZumbi12** [comment]
According docs, remainingJoinedStrings is "useful for message commands", and messages always can have player nicks, like the normal chat message, where when you use tab, auto-completes the nickname!

And i tryed with `GenericArguments.player()` and when the i have more strings on message, this don't tab complete the player name, and if i have only the nickname, this returns the player instead a string.

I think, until i can't use remainingJoinedStrings for tab player name, i ll need to create a custom CommandElement to do this.

But in my opinion, remainingJoinedStrings need to parse playernames, since your purpose is to be a message command, like our chat messages..

**Comment by FabioZumbi12** [comment]
For now, i using this to make what i want:
(cant use `args.next` because exception not allowed on lambda)
```
	public class remainJoinedStringsWithTab extends CommandElement {

		public remainJoinedStringsWithTab(Text key){
			super(key);
		}

		@Override
		protected Object parseValue(CommandSource source, CommandArgs args) throws ArgumentParseException {
            StringBuilder ret = new StringBuilder(args.next());
            while(args.hasNext()) {
                ret.append(' ').append(args.next());
            }
            return ret.toString();
		}

		@Override
		public List<String> complete(CommandSource src, CommandArgs args, CommandContext context) {
		    return Sponge.getServer().getOnlinePlayers().stream().filter(
		            play -> args.hasNext() && play.getName().toUpperCase().startsWith(args.getAll().get(args.getAll().size()-1).toUpperCase()))
                    .map(Player::getName).collect(Collectors.toList());
		}
	}
```
But still the suggestion!

**Comment by mattmess1221** [comment]
@FabioZumbi12 Be careful with that. If you have a vanish plugin installed, it won't hide vanished players from others without the permission.

**Comment by FabioZumbi12** [comment]
Added a `player.cansee(other)` check ;)

**Comment by dualspiral** [comment]
Old issue, not going to happen - if people want this I'd accept a PR.
