### ISSUE TITLE
Custom data: registerGettersAndSetters called too late

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Sponge#1677]
**I am currently running**

- SpongeVanilla version: 1.12.2-7.0.0-BETA-1

**Issue Description**
 I would like to use custom data. This issue was introduced by a recent commit in SpongeCommon. This issue is more like a question.

Here is a test repo for this issue: https://github.com/randombyte-developer/data-issue (execute the `/test` command)

This plugin simply gets any entity and tries to offer some sample data to it. How it is done in the plugin, it fails with this: https://gist.github.com/randombyte-developer/0e1096495581764b594775bc7d8bffc2

So, the `registerGettersAndSetters()` method is called too late. Okay, then I will call it earlier, but I need the instance of the manipulator for that, which isn't created yet. It think the only solution to this would be creating all possible manipulator instances in the pre init, that will be used later. But this doesn't seem like a solution. What am I doing wrong?

When should `registerGettersAndSetters()` be called?

**Comment by randombyte-developer** [comment]
@felixoi suggest "as work-around SampleKeys.BOOL.getQuery() will work, because this loads the class.. (In GameInit Event) "

**Comment by felixoi** [comment]
It's not a workaround in these words. I think everything works, there is no issue. Since API 7 you have to register the keys before data registration is done. If you outsource the key class now, you have to load the class before data registration (static fields will be initialized which calls the key builder). The other option would be registering the keys like in this [example](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/testplugins/src/main/java/org/spongepowered/test/myhomes/MyHomes.java).

Hopefully, you can understand my explanation.

**Comment by gabizou** [comment]
This is not an issue. You need to register your keys in the same init stage as your data registrations happen.
