### ISSUE TITLE
Blocks are sometimes still dropping if the block-break event is canceled

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/Sponge#1709]
**I am currently running**
- MC 1.12.2
- SpongeForge version: 2833
- Forge: 2587
- Java version: 1.8.0_131
- Operating System: Debian 9.3

- Plugins/Mods: Griefprevention Build 511

**Issue Description**
Basically, if you create a landclaim with griefprevention, the area is protected from grief.
The plugin cancels the block-break event if players trying to break a block.

This works as usual. However, there is a small chance that the block drops itself as item
But this should not happen, as the block-break is canceled.
You can see it in this video:
A player tries to break a Pixelmon PC with a very fast pickaxe. The PC drops sometimes, but the block is still there, server and client side.
https://www.youtube.com/watch?v=LFV-YZAuRvI&feature=youtu.be

No errors.

The chance is very low (Every 200 or 300th attempt) and it seems to work with all blocks.

GP Ticket: https://github.com/MinecraftPortCentral/GriefPrevention/issues/566

**Comment by ryantheleach** [comment]
My justification for High Priority is that it's a potential dupe bug.

Note for anyone investigating, the Pixelmon PC is a multiblock.

@i9hdkill when you say, works with all blocks, specifically what blocks have you tested, since the PC is a multiblock, have you been able to recreate this with any vanilla blocks? beds or reeds maybe?

**Comment by johnfriedrich** [comment]
Works with minecraft:enchanting_table and pixelmon:healer too.

**Comment by Zidane** [comment]
Not a Sponge bug, @bloodmc closed this in GP.
