### ISSUE TITLE
LaunchWrapper classloader issue

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1727]
LaunchWrapper loads every env. class by own classloader.
This classloader caches found and not found classes.
Minecraft has many libraries and these libraries can optionally depend on another libraries.
Like `log4j2` optionally depends on `Jackson`.
At minecraft startup, `log4j2` requests `ObjectMapper` class from LaunchWrapper's classloader.
There is no `Jackson` dependency in classpath at this moment. ClassLoader caches this class as not found.
After some time sponge loads plugin in to classpath. `Jackson` is inside plugins jar.
When plugin requests `ObjectMapper`, request goes in to LaunchWrapper's classloader.
Class `ObjectMapper` is cached as not found and classloader throws `NoClassDefFound`, without re-lookup.

This is classloader: https://github.com/Mojang/LegacyLauncher/blob/master/src/main/java/net/minecraft/launchwrapper/LaunchClassLoader.java
There are 2 caches named `invalidClasses` and `negativeResourceCache`.
When class not found, it will be added in to `negativeResourceCache`
https://github.com/Mojang/LegacyLauncher/blob/master/src/main/java/net/minecraft/launchwrapper/LaunchClassLoader.java#L359
Because no class bytes returned, here will be `NullPointerException`:
https://github.com/Mojang/LegacyLauncher/blob/master/src/main/java/net/minecraft/launchwrapper/LaunchClassLoader.java#L176
`catch` block catches exception and adds wrong class into `invalidClasses` cache and throws `NoClassDefFoundException`. Because `Jackson` is optional for `log4j2`, `log4j2` suppresses this exception somewhere.
After plugin loaded, plugin requests our class, classloader founds this class in `invalidClasses` cache
https://github.com/Mojang/LegacyLauncher/blob/master/src/main/java/net/minecraft/launchwrapper/LaunchClassLoader.java#L96
and thrown exception immediately.

The simplest workaround for a plugins is clearing these caches manually using reflection.

```java
try {
    ClassLoader classLoader = getClass().getClassLoader();
    Field invalidClasses = classLoader.getClass().getDeclaredField("invalidClasses");
    invalidClasses.setAccessible(true);
    Field negativeResourceCache = classLoader.getClass().getDeclaredField("negativeResourceCache");
    negativeResourceCache.setAccessible(true);
    Method clear = Set.class.getDeclaredMethod("clear");
    Object o = invalidClasses.get(classLoader);
    clear.invoke(o);
    Object o1 = negativeResourceCache.get(classLoader);
    clear.invoke(o1);
} catch (NoSuchFieldException | NoSuchMethodException | IllegalAccessException | InvocationTargetException e) {
    e.printStackTrace();
}
```
This snippet should be in plugins main class constructor. Plugins main class can't import any class, that can be in `invalidClasses` or `negativeResourceCache` caches.

This issue can occur with any plugin and any library for a plugin.

**Comment by stephan-gh** [comment]
You should never include libraries in your plugin without relocation, so this shouldn't cause issues in most cases.

**Comment by ryantheleach** [comment]
Does the Spring suite even work after being relocated? The plugin in question is basically a HUGE plugin made to just contain libraries for what I suspect is a larger server network in the making. I mean, I get that the normal rules of relocating is a good ideal, But is shadow really good enough to handle relocating libraries with potentially massive asm and reflection hacks?

I just have my doubts with how much you can get away with.

**Comment by stephan-gh** [comment]
There is not much we can do here. Launchwrapper is more or less dead, and hopefully the next solution will handle that a little bit better, or at least provide a nicer way to clear the cache.

Bundling libraries without relocation in plugins can easily cause issues as soon as two plugins bundle the same dependency with different versions. For most libraries, relocation doesn't cause any problems and will solve all potential conflicts with other plugins. At the end, this is the only option we can properly support because most aspects of class loading are controlled by Forge or Launchwrapper.

I also have to say that bundling a giant framework like Spring in a Sponge plugin sounds like a terrible idea. This is usually where you should seriously consider splitting things into a different process and only handle communication with that process from a Sponge plugin.

The only other option would be to add some kind of classloader isolation for plugins, which is quite complicated and usually causes even more issues in various other cases.

**Comment by bloodmc** [comment]
Minecrell has answered this ticket so this issue can be closed.
