### ISSUE TITLE
RespawnPlayerEvent original player inventory empty

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1730]
Original player's inventory always empty. PoC:
```java
@Listener
public void onPlayerSpawn(RespawnPlayerEvent event) {
    Player oldPlayer = event.getOriginalPlayer();
    Inventory oldInventory = oldPlayer.getInventory();
    Iterable<Slot> slots = oldInventory.slots();
    for (Slot slot : slots) {
        System.out.println(slot.getStackSize());
    }
}
```
It prints `0` for all slots.

Does this work as intended?

**Comment by XakepSDK** [comment]
Also, even with this:
```java
@Listener
public void onPlayerDeath(DropItemEvent.Destruct event, @Root Player player) {
    event.setCancelled(true);
}
```
Slots in `RespawnPlayerEvent` are empty.

**Comment by Faithcaio** [comment]
`DropItemEvent.Destruct` only handles the dropped items not the inventory change.
Also we intentionally clear the inventory before this event: https://github.com/SpongePowered/SpongeCommon/blob/6f33321bfcb596d6dba17cf918102bed392e8b53/src/main/java/org/spongepowered/common/event/tracking/phase/entity/DeathPhase.java#L176-L180

**Comment by XakepSDK** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/1398#issuecomment-309945641

**Comment by ryantheleach** [comment]
@XakepSDK Sorry for being misleading, My memory isn't the best.

**Comment by XakepSDK** [comment]
Well, @bloodmc

**Comment by ryantheleach** [comment]
https://github.com/SpongePowered/SpongeCommon/blob/6f33321bfcb596d6dba17cf918102bed392e8b53/src/main/java/org/spongepowered/common/event/tracking/phase/entity/DeathPhase.java#L195-L196

**Comment by ryantheleach** [comment]
I honestly think that's work's as designed...

If you are cancelling the drops, you are essentially saying, "Copy this to the player and restore it after death.

Just because 2 mods are providing the same soulbound mechanic twice to the same player... They both should be checking to make sure that the inventory doesn't already contain the soul bound item.

Yes it's awkward, maybe we can make the event smarter to work around it, but I don't see the issue with it causing dupes, as both mod and plugin are both instructing it to dupe...

To do otherwise is to break expectations of plugins.

Maybe we can provide some utility methods to 'restore if doesn't exist' Now I'm not sure that's going to work nicely, so I don't really have any ideas on how to do that effectively.

Someone needs to investigate a breakdown in how different forge mods implement SoulBound, and how plugins would like to do it, and work out if there are any helper methods that we can provide on the event.

**Comment by Faithcaio** [comment]
`DropItemEvent.Destruct` is NOT an inventory event. Canceling it does not affect the inventory in any way.

If you want to put dropped items back in to the player you need to do it manually.

In the latest build Items on the corpse are copied to the respawned player.

For older builds you would have to do this part yourself in `RespawnPlayerEvent`.

This is all we can do for now without completly reworking the Death related event implementation.

**Comment by XakepSDK** [comment]
`RespawnPlayerEvent` can be deprecated?

**Comment by ryantheleach** [comment]
No, `RespawnPlayerEvent` is still very useful.

It lets you know when the player Respawns. It also lets you remove data, copy data, increase stats, or remove items, update your raw entity references.

Tons of uses still.

**Comment by XakepSDK** [comment]
I think, `getOriginalPlayer` should be renamed into `getCorpse` because name can be confusing.(in api 8, in api 7 we can just mark behavior in javadoc)
