### ISSUE TITLE
Configs always on (true)? (config-enabled=false)

### ISSUE THREAD

**Issue by ziceptor** [SpongePowered/Sponge#1764]
\config\sponge\worlds\minecraft\overworld\world\world.conf

I made changes

```
world-generation-modifiers=[
        "sponge:void"
    ]
```
I left as is

`config-enabled=false`

And started the server. You generated an empty world.

forge-1.12.2-14.23.1.2586-universal.jar
spongeforge-1.12.2-2586-7.1.0-BETA-2882.jar

**Comment by ziceptor** [comment]
Sorry for bad English. Do you understand the essence of the written?

**Comment by ryantheleach** [comment]
Yes it's something we have been aware of, and should be getting looked at soon, it may even be a duplicate issue, I just didn't have time to try to dig up the original yet.

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeCommon/blob/835d8696d73154e4505a9ea339ba555bf9025d5e/src/main/java/org/spongepowered/common/mixin/core/world/storage/MixinWorldInfo.java#L719-L722

this seems to be intentional for this? other wise the call would be `getActiveConfig().getWorldGenModifiers()`

to elaborate some config options will always work regardless of config-enabled or not, as they should be able to be set without overwriting other things, namely this one, `keep-spawn-loaded` and `load-on-startup`

**Comment by ryantheleach** [comment]
@ziceptor Sorry I should have read the question better, but that's on me not you.

There are several UX (User experience) issues regarding per world configs currently, some of this behavior is intentional (because doing otherwise causes even worse issues, like the world modification not being persisted after generation)

At some point the configs need to be reorganized / re-evaluated for the structure, and what needs to inherit, and what is truly specific per world.

I'd be keen to have this particular thing in the NBT so that it persists no matter what Sponge server it's loaded on, config or not, but that's for the team to decide at a later date.

Thanks for the report, sorry I didn't read it correctly.

As it stands, this is intended, but surprising to users.

**Comment by ziceptor** [comment]
Yeah. Now I've read your thoughts on this matter. Thank You!
