### ISSUE TITLE
Feature Request: Analog of TargetReason (from Bukkit).

### ISSUE THREAD

**Issue by realGWM** [SpongePowered/Sponge#1806]
Bukkit has `TargetReason` which allows to check, why agent (entity) selected target (other entity).
Sponge's `SetAITargetEvent` doesn't have such analog.
It makes impossible to discover why entity selected other entity as target.
Bukkit link: https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/event/entity/EntityTargetEvent.java#L79
Also, there is no `EventContextKey` for it.

**Comment by gabizou** [comment]
I'd imagine there's going to be some interesting heuristics, but this should be likely moved to API because it needs support for it.

thoughts, @Zidane ? I'm thinking this is more cause object tracking that needs to be provided, versus what the enum provides.

**Comment by realGWM** [comment]
I did not know what to choose between Common or API, and I chose Common, so:
Do I need to create new issue on API?
And should I close this one?

**Comment by gabizou** [comment]
To answer the question of whether it belongs in Common or the API is this: How do you as a plugin developer intend to use this "feature" port of the enums? Is it through an enum type from the event context? from the event? from additional causes that can include things like "oh, target change caused by player, itemstacksnapshot.... the player attacked the entity?" is the sort of question I have for you. Because if it's something that is cause or context related, we can keep it in common, but if you need a class representation for a "type", we'll need to make an issue to add it to the API.

**Comment by realGWM** [comment]
Okay, I think “class representation” would be nice! Should I close this issue, after opening new one on API?

**Comment by gabizou** [comment]
yes.
