### ISSUE TITLE
World generator crashes at large world sizes!

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/Sponge#1883]
This issue was originally submitted by @githubl0ver69 in [SpongePowered/SpongeAPI#1809](https://github.com/SpongePowered/SpongeAPI/issues/1809).
___
[Referred to you from the Nucleus team @  #1136](https://github.com/NucleusPowered/Nucleus/issues/1136)

**My problem:**
> Short version: Can't generate large worlds because the server crashes.
> 
> Long version: I can only generate a world so large before the server inevitably crashes with an "java.lang.OutOfMemoryError" exception. I don't understand programming so I'm wondering if there's a possible resolution to this.
> 
> The following commands I'm attempting to type with Nucleus:
> ```
> world border set "Survival" 0 0 102400
> world border gen "Survival"
> 
> ```

**Nucleus's response:**
> 
> Nucleus simply invokes the Sponge world pre generator, so it's down to that, it's not Nucleus. It tries to manage the memory but sometimes it just can't....
> 
> ...Ultimately, not a Nucleus problem.

**Comment by phit** [comment]
@githubl0ver69 please add versions and logs
though in the end I doubt there can be done much on the Sponge side, pregeneration due to its nature will always take a lot of memory and for huge areas, regular restarts during the process to free up memory are simply needed

**Comment by Niko-sk2x** [comment]
There is no reason at all to keep the whole pregenerated area in memory, so restarts shouldn't be required. If sponge doesn't correctly unload the chunks, this is sponge issue. I know vanilla has a limit on how fast it can unload chunks, but it's unlikely any computer can generate chunks fast enough to exceed that, and it's likely sponge removes that limit.

**Comment by phit** [comment]
@Barteks2x you can achieve the same thing in vanilla, theres command block scripts to pregenerate worlds.. even those will OOM eventually. why do you think stuff like [this ](https://minecraft.curseforge.com/projects/chunkpregenerator) exists? try the build in forge command to pregen and look at the memory consumption after like 30min..

this has nothing to do with what sponge does, if anything pregen is faster with sponge than without thanks to sponge's async lighting. if you seriously think restarts arent required for big maps during pregen, I'm sorry then you are just simply wrong.

**Comment by Niko-sk2x** [comment]
Then why I can fly around as a player for thousands and thousands of blocks, generating more and more terrain, without ever running out of memory? And there really isn't much difference in how Minecraft generates terrain for players. I don't know why it runs out of memory but this definitely isn't something that should happen, unless all of the chunks are generated in a single tick (which is a very very bad idea).

**Comment by Niko-sk2x** [comment]
I actually investigated it and it turns out the reason (at least for forge generate command) is that AnvilChunkLoader can't write the chunks to disk fast enough. Maybe blocking the server thread if `chunksToRemove` has too much stuff would be a good idea? This would have the effect of lagging the server if too many chunks are getting unloaded, but it would prevent such out of memory errors. And simply generating chunks less frequently than once per tick would fix it too.

**Comment by githubl0ver69** [comment]
I created a feature request for Nucleus: https://github.com/NucleusPowered/Nucleus/issues/1137. Basically, if we could restart the server to refresh everything and have the chunk generator remember where it left off, then that would be one resolution to the problem at and here.

**Another idea:** I don't know Java but another resolution I thought of was generating in regions. In other words, I define a radius and generate a square from it. Then I set a new radius and generate another square beside the one one. Rinse and repeat. The only thing I need to figure out here is the math so that I don't have to manually calculate where the next center of the radius should be. This way, I can have a script run that will a.) automatically restart the server after each generation b.) send a command to set the radius and start generation for the next chunk.

**Comment by JBYoshi** [comment]
I think I know what your problem is. Sponge adds an optimization to keep chunks in memory for a short period of time after they become unused. Usually, this is intended to improve performance when players keep moving into and out of a few chunks. However, when used with large-scale pregeneration, it can easily become problematic.

To work around this, you can change the `chunk-gc-load-threshold` in [the Sponge configuration](https://docs.spongepowered.org/stable/en/server/getting-started/configuration/index.html) to a value like 1000 and restart the server - this will force all extra chunks to be unloaded whenever 1000 chunks are loaded simultaneously. If the server still crashes, decrease that value. Once you're done, change it back to 0.
