### ISSUE TITLE
Question about Sponge patches and a vanilla bug

### ISSUE THREAD

**Issue by ZombieHDGaming** [SpongePowered/Sponge#1898]
Hello,
I work with Dimensional Development, a team responsible for the revived DimDoors and a new mod called VanillaFix. In VanillaFix, we use mixins to patch a bug in the NetHandlerPlayServer which is caused by Vanilla itself for an unknown reason. The vanilla bug ([https://bugs.mojang.com/browse/MC-98153](https://bugs.mojang.com/browse/MC-98153)) is something we've tried to fix within our mod, but due to how Sponge is, it's not a fan of use messing with a class that it already messes with. So my question is, does Sponge by any chance already fix this issue so we can make it optional on our end so Sponge doesn't throw a massive error in console (even @Waterpicker agrees on that, it's a big error), or could there be a way to incorporate this bug fix into Sponge, if it isn't already there, so there won't be an issue on either side should someone decide to throw Sponge and VanillaFix together?

Cheers,
Zombie

**Comment by phit** [comment]
might be helpful to link the patch in question https://github.com/DimensionalDevelopment/VanillaFix/blob/master/src/main/java/org/dimdev/vanillafix/mixins/MixinNetHandlerPlayServer.java#L77

**Comment by Aaron1011** [comment]
> but due to how Sponge is, it's not a fan of use messing with a class that it already messes with

@ZombieHDGaming: Mixin is actually designed to allow multiple different mixins (which may come from different mods) to target the same method, as much as is possible. The problem is that VanillaFix is using an `@Overwrite`, which by design prevents any other mixins from modifying that method.

Depending on what changes you need to make to `NetHandlerPlayServer#processPlayer`, it should be possible to use targeted `@Inject` and `@Redirect` handlers instead of an `@Overwrite`. Unfortunately, it's somewhat hard to tell what changes you've made to the method.

If you'd like to try to make your mod compatible with Sponge, it would be very helpful if you could comment your `@Overwrite` to indicate exactly what changes you've made. In Sponge, we use `// Sponge start` and `// Sponge end` comments to indicate blocks of code that we've modified. Whatever style you want to use is fine, as long as it makes it clear exactly what changes you've made.

If you can do that, I'd be happy to work with you to convert your `@Overwrite` into individual `@Inject` handlers. If necessary, I can also tweak the injection points that Sponge uses in order to be better compatible with your mod.

**Comment by ZombieHDGaming** [comment]
@Aaron1011 Thank you for the insight. I myself didn't write the code, as @Runemoro learned how to use Mixins, whereas I haven't yet (It's on my list of stuff). I have forwarded it to him, but if you want specifics about what we change in the method, I can actually tell you.

```java
d9 = d6 - this.player.posZ;
                            d11 = d7 * d7 + d8 * d8 + d9 * d9;
                            boolean flag = false;

                            if (!this.player.isInvulnerableDimensionChange() && d11 > 0.0625D && !this.player.isPlayerSleeping() && !this.player.interactionManager.isCreative() && this.player.interactionManager.getGameType() != GameType.SPECTATOR)
                            {
                                flag = true;
                                LOGGER.warn("{} moved wrongly!", (Object)this.player.getName());
                            }

                            this.player.setPositionAndRotation(d4, d5, d6, f, f1);
                            this.player.addMovementStat(this.player.posX - d0, this.player.posY - d1, this.player.posZ - d2);
```
This is the vanilla method and what it does. Rune mentioned this on the Mojang bug tracker:
>The position seems to get reverted right after the teleport: this.player.setPositionAndRotation(d4, d5, d6, f, f1); Removing that line fixes the problem. Disconnecting right after changeDimension (by setting a breakpoint) causes the player to have the dimension changed but not the position, which could even be abused intentionally by some players.

So, I'm assuming besides that bug, he also did something for a few other bugs. I don't know the exact specifics of what he has done to the method, but that's what I know thus far.

**Comment by Runemoro** [comment]
@Aaron1011 Very little of the vanilla logic remains after all my changes, I almost rewrote the method from scratch, changing the way teleportation is handled (done immediately rather than on confirmation from client), and completely changing the control flow of the checks done to the packet (check before moving rather than move then revert if the check fails).

However, the injection point of the mixin (the queuedEndExit field) is one of few things that remains, so if it would be possible to allow sponge to inject its mixin anyway, then that should work with no problem. Is there some annotation, or something else we can do, to tell sponge that its mixin should still be injectable in the new, rewritten, method?

**Comment by phit** [comment]
closing this, as its not a bug, feel free to still use it for further communication
