### ISSUE TITLE
Dupe glitch with portal teleportation

### ISSUE THREAD

**Issue by fhntv24** [SpongePowered/Sponge#1903]
**I am currently running**
- SpongeForge version: 7.1.0 3002/3065 ( tested both )
- SpongeVanilla version: not tested
- Java version: openjdk version "1.8.0_151"
- Operating System: Ubuntu 16.04

- Plugins/Mods: forge, fml, mcp, sponge.

**Issue Description**
While teleporting Entity using nether portals, sometimes it could appear twice on the other side. Seems to be easier when other side is unloaded. It's also might be position related thing, so building multiple portals is recommended. Removing SpongeForge mixin into Entity does fix this.

**Some explanation**
After calling `EntityUtils.EntityUtil.transferEntityToDimension()` entity isn't being marked as dead, as this method does not clone entity as vanilla does. This might be root cause of this glitch, but I'm not 100% certain on this.

**Comment by bloodmc** [comment]
@Aaron1011 Please take a look at this.

**Comment by Aaron1011** [comment]
@fhntv24: I'm unable to reproduce this. Are you able to trigger this bug consistently? If so, how?

**Comment by Dysthymic** [comment]
Using GP to disable portal entry as a temporary fix. Here's the glitch in action. We had a player with Shulker boxes full of insane rares by doing this. It is very hard to get the hang of and reproduce, but if you do it over and over you'll eventually get the timing right
https://gyazo.com/09d1946c18f2ab0b4aaf5974cb86a4ac
https://gyazo.com/8b33e0347d2476a1c2947b7c9dd609e9

**Comment by Aaron1011** [comment]
@Dysthymic @fhntv24 Are either of you able to reproduce this on the latest (not reccomended build) of SpongeForge?

**Comment by fhntv24** [comment]
@Aaron1011 I wasn't able to reproduce it on latest SpongeForge version. I can send test map, if intresting, but building portal across chunk borders ( on "incoming side", aka other side from where you are throwing items ) does help.
Same map, same spot, same steps.

I will send my tester team to test, but this issue should be closed.

**Comment by runescapejon** [comment]
So this issue happen to me very odd behavior because it's was very strange one you can only perform this dupe bug with having SpongeForge and specific level.dat you get a nether portal and you grab a minecart chest put the item you want to dupe with in there then push the minecart chest through the portal and inside of the nether world it push out two minecart chest that contain the one has the item you put in and the other duplicated it here a gif https://gyazo.com/1c674ca0f89e53e7ea3dc0105bb71dd4 and this one https://gyazo.com/6686856aee775469c4a8bbd9cbfcf1ec I have no idea what had happen to level.dat but here is a copy it's below also i have spongeforge-1.12.2-2768-7.1.5-RC3509 also have forge-1.12.2-14.23.5.2796-universal also effected backup level.dat best way to fix the issue is to delete your own level.dat which is bad 

[level.zip](https://github.com/SpongePowered/SpongeCommon/files/2670249/level.zip)

@Aaron1011 to perform this just grab this level.date then get spongeforge build a nether portal then place rails lead to the nether portal place the minecart chest put the item you want to duplicate with inside of the minecart chest then push the minecart into the nether portal then you have two minecart chest with both item inside but you can only perform this one time but if you restart the server you can then perform it again.

also this issue seem to be related to https://github.com/SpongePowered/SpongeCommon/issues/2103

**Comment by JBYoshi** [comment]
@runescapejon I just fixed #2103. Try again on RC3511 (when it comes out in a few minutes) and see if it's still happening.

**Comment by runescapejon** [comment]
@JBYoshi  Yes can confirm it's fixed thanks you very much.
