### ISSUE TITLE
EntityArchetypes not accepting Data Keys properly

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/Sponge#1927]
This issue was originally submitted by @Xenmai in [SpongePowered/SpongeAPI#1838](https://github.com/SpongePowered/SpongeAPI/issues/1838).
___
Hi there.

I'm having an issue when giving keys to entity archetypes. I've tried both inside the builder using `EntityArchetype.Builder#set(Key, Value)` and with an already built **EntityArchetype** using `DataHolder#offer(Key, Value)`. The latter returns an **unsuccessful DataTransaction**, even though I'm checking if the **DataHolder supports the key** first (and it does).
So it seems **EntityArchetypes are not accepting Data Keys** at all.

Also on a side note, when creating an entity with `EntityArchetype#apply(Location<World>)` and then spawning it, I get an error about Minecraft not being able to **track the entity** properly. The full error can be found here: https://pastebin.com/0Y0Tnwhz

Thanks a lot for your help and have a nice day!

Note: I'm using **spongevanilla-1.12.2-7.1.0-BETA-48.jar**.

Note 2: I've checked some **SpongeCommon** code (this issue should probably be moved there, sorry), and inside SpongeEntityArchetypeBuilder the `#set(Key, Value)` and `#set(Value)` methods seem to use a **NBT processor** of type "_Tile Entity_", not an "_Entity_" one. Could this be causing the issue? I'm confused as to why that method seems to be coded to work just for Tile Entities, can't I give keys to an Archetype of type Entity? Thanks again for your time!

**Comment by Xenmai** [comment]
Update: The "Entity Tracking" error is due to `EntityArchetype#apply(Location<World>)` already spawning the entity, so spawning it again is obviously going to result in an error. So that's solved.

Other than that, the main error still stands: Entity Archetypes not accepting data at all. I've tried some other methods, like setting raw data directly from a DataContainer (instead of setting each key-value pair independently), but that didn't work either.

Just trying to give as much information as I can. Thanks again for your time!

**Comment by JBYoshi** [comment]
I think I found the real issue. When entity archetypes were implemented, `supports()` returned `true` for any unknown data because of the possibility of custom data. In reality, however, neither custom data nor vanilla data (https://github.com/SpongePowered/SpongeCommon/issues/950) appears to be implemented for archetypes at the moment... not sure what happened to that. All I see implemented is `FlyingData`, and just the manipulator for that.

**Comment by gabizou** [comment]
Part of the issue is that we haven't written the data implementation to read data manipulators from raw nbt. When we were implementing archetypes, we started writing the system for `NBTDataProcessor`s, but no one ended up implementing them.

**Comment by ryantheleach** [comment]
@gabizou are they ready to just smash out in bulk? or is there supporting code missing?

**Comment by gabizou** [comment]
A little of both. I haven't written it to work yet, but the processor for retrieving the not Is there.

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/950
