### ISSUE TITLE
Player#closeInventory() warns in console

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Sponge#1936]
SpongeVanilla 1.12.2-7.1.0-BETA-57
SpongeAPI 7.1.0-SNAPSHOT-43d84967

When trying to close the player's inventory while the player has something in hand(sticking to the mouse, you know) it doesn't close:

```
This player is currently modifying an open container. This action will be delayed.
```

[Here](https://github.com/SpongePowered/SpongeCommon/blob/989a541950ef28198015e626dfe38fa5539cb9d6/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java#L703) it is delayed for a next try.

**Comment by randombyte-developer** [comment]
Turned out that I was cancelling close events and the logic wasn't quite right.

But ok, now the closing works but that warning message is always there. How can I check the

```
((IMixinContainer) this.openContainer).isInUse()
```

myself in a plugin? Or how to deal with this warning?

**Comment by Faithcaio** [comment]
If you are in any ClickInventoryEvent the Container is in use.
If you were to close the inventory before the event returns to Sponge, Sponge cannot apply changes to the inventory anymore (like cancel/slottransactions/cursortransaction). 
And because I'm nice instead of throwing an exception I only print a warning and schedule it for the next tick. (This might change in API8)

To remove the warning schedule the inventory close operation yourself.
