### ISSUE TITLE
README is not clear on just building Sponge.

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Sponge#194]
The README states that setting up the Sponge project for importing into an IDE requires running `gradlew setupDecompWorkspace` but for [building](https://github.com/spongepowered/sponge#building), it is unclear whether running `gradlew setupDecompWorkspace` is necessary.

Instructions need to be clearer for the general populace wanting to simply build Sponge without an IDE involved.

**Comment by simon816** [comment]
I think it would be better if the `build` task depends on the `setupCIWorkspace` task

**Comment by gabizou** [comment]
> I think it would be better if the build task depends on the setupCIWorkspace task

Then running the `build` task in an IDE would cause a `setupCIWorkspace`, which is a nono. Both `setupCIWorkspace` and `setupDecompWorkspace` need to be run *before* `build` since it involves setting up dependencies and such.

**Comment by kenzierocks** [comment]
Also, there's a reason (ask @AbrarSyed) that there is not a dependency between those tasks.

**Comment by AbrarSyed** [comment]
if no setup has been done, build implicitly depends on setupCIWorkspace. IF a setup has already been done, then build uses the existing MC libraries instead of doing a setup at all.

Unfortunately, sponge uses the Shadow plugin. The shadow plugin resolves dependencies too early, before the MC dependency is created. Thus the setup and build tasks must be executed in separate gradle runs. However it should not matter which setup was done, as long as A setup was done.

**Comment by simon816** [comment]
Could changing the shadow plugin be an option? Or create the MC dependency earlier?

**Comment by Zidane** [comment]
Covered in https://github.com/SpongePowered/Sponge/commit/8899a6c377f359f83ee64cc6d8d00bac1201787f
