### ISSUE TITLE
sponge command throwing error with no subcommand

### ISSUE THREAD

**Issue by phit** [SpongePowered/Sponge#1953]
**I am currently running**

- SpongeForge version: 7.1.0-BETA-3218
- SpongeVanilla version: 1.12.2-7.1.0-BETA-67

- Plugins/Mods: /

**Issue Description**
type `/sponge` in console, get reply 

```
[02:41:45] [Server thread/INFO]: Invalid subcommand state -- no more than one mapping may be provided for child arg child0
```

expected result
```
[02:40:10] [Server thread/INFO]: Not enough arguments!
[02:40:10] [Server thread/INFO]: Usage: /sponge which|audit|plugins|timings|heap|version|[--global|-g] [--world|-w <world>] [--dimension|-d <dimension>] reload|chunks|tps|save|config
```

**Comment by SimonFlash** [comment]
The problem here is that Sponge's `CommandElement` for non-flag children is created with a fallback executor but not a `CommandElement` to handle the parsing for it ([here](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/command/SpongeCommandFactory.java#L164-L165)). This causes the `parse` method to return without handling the verification that a subcommand has been specified as there's no fallback element ([here](https://github.com/SpongePowered/SpongeAPI/blob/d5f1171eb1ede4fe12efe731271eb3ad5a7cf48d/src/main/java/org/spongepowered/api/command/args/ChildCommandElementExecutor.java#L177-L184)).

The solution to this is to create the `ChildCommandElementExecutor` with the delegate element as both the fallback executor and fallback element.

```java
final ChildCommandElementExecutor flagChildren = new ChildCommandElementExecutor(null);
final ChildCommandElementExecutor nonFlagChildren = new ChildCommandElementExecutor(flagChildren, flagChildren, true);
```

**Comment by ryantheleach** [comment]
Considering it was working previously, is @SimonFlash 's suggestion a work around? or is the current behavior unintended given the current command code?

**Comment by dualspiral** [comment]
Workaround should work - at least ish, though I don't think it'll give the correct usage (I think, haven't tested it, this is skimming code while in bed), reasoning is not completely correct. 

Note that these child commands are not written in the normal way. [The children arguments are specified differently](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/command/SpongeCommandFactory.java#L196-L200), so the expectation is that these arguments should create the usage. As `firstParsing` is creating the commands, _that_ should bail without parsing any commands - obviously it is not. This is probably because I've got some check for standard child commands that has messed up in this case, likely due to improper validation that Simon suggested.

I'll fix it either tonight or this weekend.
