### ISSUE TITLE
Projectile MoveEntityEvent

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Sponge#2004]
**I am currently running**
```
➜  vanilla1.12.2 java -jar spongevanilla-1.12.2-7.1.0-BETA-86.jar -v
SpongeVanilla 1.12.2-7.1.0-BETA-86
SpongeAPI 7.1.0-SNAPSHOT-8976964c
```

**Issue Description**

Neither the `MoveEntityEvent` nor the `LaunchProjectileEvent` fire for arrows and snowballs, probably all projectiles.

Tested by simply logging the moved/launched entities with

```
@Listener
public void onMove(MoveEntityEvent event) {
  System.out.println(event.getTargetEntity().getType().getId());
}
```

and the same for the `LaunchProjectileEvent`. The move event shows all player/mobs/animals/xp orb 
 etc. movements but not arrow nor any snowballs. The `LaunchProjectileEvent` doesn't print anything.

**Comment by ImMorpheus** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/1397

**Comment by randombyte-developer** [comment]
Right, thanks, somehow couldn't find that issue. Then this issue will just be for the move event of projectiles which doesn't seem to be targeted to fixed in #1769.

**Comment by JBYoshi** [comment]
From #2348, this is caused by the following line:

https://github.com/SpongePowered/SpongeCommon/blob/b1638839846a2740e2e5a95f5fe8b7c77341ccd8/src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java#L911

The original reason it was skipped was to improve performance, but I'm not sure how relevant that is. Projectiles are short-lived, and items don't throw move events after they've been tossed (unless they're being deliberately moved via pistons, water, or similar objects).

**Comment by parlough** [comment]
I'm personally of the opinion we should enable support for both for now. If there are any problems once re-enabled we can revisit the problem. Most plugins likely don't need to support these types of entities, and obviously can and should fail early if the entity is not a type they care about.

**Comment by ImMorpheus** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/ebd33301e8d7256215026081335a9e5d68e43972
