### ISSUE TITLE
Sponge commands not including flags

### ISSUE THREAD

**Issue by SimonFlash** [SpongePowered/Sponge#2006]
*pinging @dualspiral per request by blood*

[This commit](https://github.com/SpongePowered/SpongeCommon/commit/f6acf932d124f7a2d9c32f2069aa49ed508dd713) created a situation where subcommands with the `tracker` flag (handled by `trackerFlagChildren`) are parsed after `firstParsing` has parsed `flagChildren`. Because `CommandFlags` removes the flag from the arguments [here](https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/command/args/CommandFlags.java#L83), they don't exist to be parsed and adding into the context the second time around.

A quick fix for this is to remove one of these levels so flags are only parsed once. Further down the line, changes need to be made in API to prevent cases like this from happening. Long-term, I believe that these commands need to be redesigned as there is plenty of room for improvement to make them more functional and user-friendly.

**Comment by dualspiral** [comment]
What is the current problem with the command? You explain where the problem is, but not how it manifests...

**Comment by dualspiral** [comment]
Actually, I know what's going on, and while you point at that commit, the problem has been long standing because of how flags are parsed, it was just obscured by another bug. It was in fact [this commit](https://github.com/SpongePowered/SpongeAPI/commit/8976964c1038066d3555ac6fb613ed3839037090) that exposed the issue by fixing the context for firstParsing. As you point out in your other issue, yes, the correct solution is to use a snapshot system like to command contexts, and that's exactly what I'll do (and I have the start of a patch doing this). 

Better to do it right now than just to patch it, you never know who else might be having this issue.
