### ISSUE TITLE
 DeathUpdateState discarding item drops from Entity#entityDropItem

### ISSUE THREAD

**Issue by pau101** [SpongePowered/Sponge#2007]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3206
- Java version: 1.8.0_121-b13
- Operating System: Microsoft Windows 10 Home
- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, LLibrary, Mowzie's Mobs

**Issue Description**
 `DeathUpdateState` silently discards item drops captured from `Entity#entityDropItem` during `EntityLivingBase#onDeathUpdate`.

This was encountered with entities from Mowzie's Mobs through a user who reported this to me (BobMowzie/MowziesMobs#47). Our mobs are intended to drop items after their death animation, which we do so during the death update.

While tracking this issue down I noticed the behavior `DeathUpdateState` has for `PerEntityItemDropSupplier` captures, which is logging the them as errors. Which is similar to behavior that exists for different unwind logic in various states. This brought me to think, how can a state deem certain behaviors as errors? I am interested in an explanation, as this, on the surface at least, appears to force limitations.

The items here are lost from `DeathUpdateState` not handling the `PerEntityItemEntityDropSupplier`, which is what contains the item entities from `Entity#entityDropItem` at this time.

A couple of other classes that appear to have curious logic are `InteractionPacketState`, which handles `PerEntityItemDropSupplier` the same while ignoring `PerEntityItemEntityDropSupplier` and `CommandState` which handles `PerEntityItemDropSupplier`, but and ignoring `PerEntityItemEntityDropSupplier`.

Something which further intrigued me was the apparent lack of use of `PerEntityItemDropSupplier` for capturing. I have not been able to locate any place which offers data to that supplier, only the alternate `PerEntityItemEntityDropSupplier` through `SpongeImplHooks#capturePerEntityItemDrop`. I am quite curious about this, what is the motivation?

**Comment by gabizou** [comment]
Oh hey, somehow this issue got left aside. Some core structure changes have been taking place on the capture side of the tracking code. I'll investigate further, likely after I get #2155 fixed with https://github.com/SpongePowered/SpongeCommon/pull/2163.

**Comment by gabizou** [comment]
Reviewing SpongePowered/SpongeForge#2297, I believe the fix is now actually done for that which should cover this issue. 

To explain the *why* there's multiple types of captures:
We have the common understanding that Sponge will keep track of a `List` of `Entity` and `BlockSnapshot` objects that are either changing or spawning in a `World` during any specific `PhaseState`. `PhaseState` itself is just a devised system to associate a more precise game state to allow Sponge to associate extra information for event `Cause`s, like whether an entity is spawning x items but that entity was attacked by player b and the entity was owned by player a. This is all fine and dandy when you consider the surface attempt to just track all entity spawns and item drops and block changes during a particular phase.

Now consider, when an explosion occurs, multiple items are being dropped, multiple blocks are being changed at once, and multiple entities are being killed/spawned. If you keep just one list to keep track of all entities spawned, you lose track of where each entity was being spawned from. So, I started using [`Multimap`](https://github.com/google/guava/wiki/NewCollectionTypesExplained#multimap) to be able to keep track of each individual entity/block position spawning entities during a particular phase that I didn't want to *enter another phase that would have different information passed to events* so the appropriate causes are tracked with those entities that will be spawned and events to be thrown. In the end, what we end up with is the possibility of having multiple states where they *can* keep track of not just block changes, but the reactionary block changes, entity spawns, item drops, etc. of those block changes. The same will apply to states that have the same treatment for entities as well, in which case, is the root of the commit that fixed SpongePowered/SpongeForge#2297 where `DeathUpdateState` was not processing those captures within that multi map.

After writing this response, I have the belief that this issue can be closed, but I'll allow for verification from OP before closing in a weeks time.

**Comment by pau101** [comment]
Looks all good now!
