### ISSUE TITLE
Means for replacing dropped items in ChangeBlockEvent.Break

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/Sponge#2015]
For ChangeBlockEvent.Break class required means of replacing or removing dropped items. I need to remove the block and at the same time replace the dropped items or remove them and spawn my items.

**Comment by gabizou** [comment]
You can do this by listening to `SpawnEntityEvent` and checking for the `SpawnTypes.BLOCK_SPAWNING`, as well as other aspects of the cause that are reliable.

You can see the implementation doing this [here](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/event/tracking/TrackingUtil.java#L774) and [here](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/event/tracking/TrackingUtil.java#L698).

I don't think this has ever really been a problem before, since @bloodmc has even implemented such things for GriefPrevention (at least, cancelling spawning but allowing block edits).

**Comment by Lignium** [comment]
This event is not called when the blocks breaks down in the survival mode by hands of player. It can be called, for example, if the lower block breaks down, which will cause a breakdown of the upper one. But I cannot guarantee that the block was broken, because there is no ChangeBlockEvent.Break in the causes.

UPD: Also does not work DropItemEvent.Destruct.

**Comment by Lignium** [comment]
This issue may be closed. As you wrote I need to listen to SpawnEntityEvent which as you know is somewhat broken (https://github.com/SpongePowered/SpongeCommon/issues/2144).
