### ISSUE TITLE
org.spongepowered.api.item.inventory.Slot.getStackSize reporting incorrect size

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/Sponge#2016]
This issue was originally submitted by @virustotalop in [SpongePowered/SpongeAPI#1872](https://github.com/SpongePowered/SpongeAPI/issues/1872).
___
The getStackSize method in Slot is reporting the wrong stack size. According to the documentation when a slot is empty the method should return -1, however when running a plugin on spongevanilla-1.12.2-7.1.0-BETA-93 the stack size that is being reported is 0. This occurred when referencing a player's main inventory and iterating through each slot. I would have opened a pull request but I am not sure what is the intended behavior. Thank you for your time and I hope this issue gets resolved. Sorry if I should have reported this on the SpongeVanilla repository, I wasn't sure. Reference code below.

```java
public static int getFreeInventorySlots(Player player)
{
     int emptySlots = 0;
     Iterable<Slot> slots = player.getInventory().query(QueryOperationTypes.INVENTORY_TYPE.of(MainPlayerInventory.class)).slots();
     for(Slot slot : slots)
     {
          if(slot.getStackSize() <= 0)
               emptySlots++;
     }
		
     return emptySlots;
}

**Comment by Faithcaio** [comment]
Imo it makes no sense to return -1 for empty 0 is just fine.

**Comment by ryantheleach** [comment]
It was previously -1 due to previous editions of Minecraft acting oddly with 0 sized itemstacks.

To keep 0 requires an API change of contract.

-1 is the correct response, until it's changed in the API.

Note, because changing this is a subtle change of behavior, plugins arn't going to be warned when the behavior changes due to the signature changing.

Are they expecting -1 per the docs, or are they expecting 0 because that's likely what the behavior has been since empty item stacks was refactored (pending proof of when this change was introduced)

**Comment by virustotalop** [comment]
Sorry if the issue is unclear in the original post. The documentation for getStackSize states that if the slot is empty -1 should be the returned value however the current returned value is 0. I initially expected the returned value to be -1 while reading the documentation but I tested it and the stack size that was being returned was 0.

From the current docs
> Returns:
    the stack size or -1 if this slot is empty 

The code below is what was originally used.
``` java
public static int getFreeInventorySlots(Player player)
{
     int emptySlots = 0;
     Iterable<Slot> slots = player.getInventory().query(QueryOperationTypes.INVENTORY_TYPE.of(MainPlayerInventory.class)).slots();
     for(Slot slot : slots)
     {
          if(slot.getStackSize() == -1)
               emptySlots++;
     }
		
     return emptySlots;
}
```
The above code returned 0 as all item slots were of size 0 or more.

**Comment by Faithcaio** [comment]
For API8 it will not be -1 for sure.
Question is should we just change the API7 javadocs to reflect what it really returns.

Also why count the empty slots yourself? 
`inventory.capacity() - inventory.size()`

**Comment by Faithcaio** [comment]
`Slot#getStackSize` is the same as `Inventory#totalItems` so i'll remove it completly.
For API7 I "fixed" the Javadocs. Returning -1 makes no sense.
