### ISSUE TITLE
Inventory modifications from scheduled tasks are sometimes included in inventory events

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Sponge#2030]
Plugins often modify a player's inventory, or an open GUI, from a (synchronous) scheduled task. However, if these modifications occur during the same tick as an inventory packet, the plugin's modifications may be captured and included in the event.

From what I can see, the issue occurs when `detectAndSendChanges` is not called between the scheduled task and the packet phase unwinding. This causes the scheduled task's changes to be detected and captured along with the changes caused by the actual inventory click.

One solution might be to call `detectAndSendChanges` after we run our scheduled tasks. However, this could be unnecessarily expensive, since we'd be calling it twice per tick per open container. Alternatively, we could handle inventory modifications done through the API in a special way, ensuring that they never end up captured in `detectAndSendChanges`.

**Comment by Faithcaio** [comment]
It gets captured in `detectAndSendChanges` because thats what sends the changes to the Client as well.
So probably just calling `detectAndSendChanges` an additional time after scheduled tasks were run is the solution.

Should not be too bad for performance. Players do this already every tick.

**Comment by gabizou** [comment]
Just to add on, interaction events that get cancelled server side already have to forcibly send the player's inventory back to the client to avoid client ~~stupidity~~ misrepresenting expectations (like cancelling bucket placement/filling requires sending the full inventory down the wire because we don't know which slot a new item stack was sent into).

I understand it may not be cheap to do, but `detectAndSendChanges` is pretty cheap to call whenever we need to avoid cross contamination of plugin logic and phase tracker logic.

**Comment by Faithcaio** [comment]
We already had markDirty() on Fabrics so just needed to use it.
For Containers (open Inventories) it will immediatly call detectAndSendChanges. So it should not capture anything.
For the (closed) Player Inventory I check for dirty state after scheduled Tasks ran and then run detectAndSendChanges when needed.

I think this should cover it.
