### ISSUE TITLE
Problem with creating a local message channel.

### ISSUE THREAD

**Issue by RussianJeb** [SpongePowered/Sponge#2063]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3403
- Java version: Java 8 update 181 64 bit
- Operating System: Windows 10 Enterprise

- Plugins/Mods: Not used

**Issue Description**
I’ve been trying to create a local channel using different methods. At this moment I’m using this one:
```java
@Listener
public void onChat(MessageChannelEvent.Chat event, @Root Player player) {
    event.setChannel(MessageChannel.fixed(player.getNearbyEntities(30)
            .stream()
            .filter(Player.class::isInstance)
            .map(Player.class::cast)
            .collect(Collectors.toList())));
}
```

But I found a problem. When many objects like XP bottles and mobs are in a radius than I’ve pointed and you’re flying another way and then turning back, messages can’t be sent or channel can’t be created. I’ve tried many methods but problem remained.

**Comment by ryantheleach** [comment]
@bloodmc There's been several issues relating to **different** symptoms of `max-entities-within-aabb` causing unexpected behavior for people. Should we maybe disable it by default?

@Marsadnes I'm 99% sure this is due to max-entities-within-aabb in global.conf

https://docs.spongepowered.org/stable/en/server/getting-started/configuration/sponge-conf.html?highlight=max-entities-within-aabb

max-entities-within-aabb is supposed to be an optimization to help when many entities are colliding, but as AABB bounding boxes are a useful optimization for getting nearby entities, mods and plugins end up unintentionally using it.

# Workaround

Advise people who need to use local chat to set `max-entities-within-aabb` to zero. 

### OR

 Don't filter the nearby entity list for players, instead opting to filter the global online player list by distance.

If you want a distance comparison that's fast, use https://flowpowered.com/math/com/flowpowered/math/vector/Vector3d.html#distanceSquared-com.flowpowered.math.vector.Vector3d-

For what it's worth, I suspect iterating all players that are online, rather then nearby entities is going to be faster in most cases, depending on how many entities are around.

**Comment by dualspiral** [comment]
The collisions module has been completely rebuilt and this should no longer be an issue. If it is, please open a NEW issue with as much information as possible.
