### ISSUE TITLE
ResourceBundleTranslation is half broken

### ISSUE THREAD

**Issue by mmis1000** [SpongePowered/Sponge#2091]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3415
- Java version: OpenJDK 8
- Operating System: Linux

- Plugins/Mods: AppleSkin, JMFixer, JourneyMap, RandomPatches, NPCs, SpongePrometheusExporter, VillageMarkerSponge

**Issue Description**

The `ResourceBundleTranslation` is half broken, and can't be really be used in `Text` API, see example following

**code to repoduce**
```kotlin
// command.kt
        val testTranslate = ResourceBundleTranslation("plugin.sword") {
            ResourceBundle.getBundle("test")
        }
        val str = testTranslate.get(Locale.US)
        val plain = Text.of(testTranslate).toPlain()
        val serialized = TextSerializers.JSON.serialize(Text.of(testTranslate))
        val deserialized = TextSerializers.JSON.deserialize(serialized)

        src.sendMessage(Text.of(str))
        src.sendMessage(Text.of(plain))
        src.sendMessage(Text.of(serialized))
        src.sendMessage(
                Text.of(
                        TextSerializers.FORMATTING_CODE.serialize(deserialized)
                )
        )
```

```properties
# test.properties
plugin.sword=plugin test language
```

**expect**
```
plugin test language
plugin test language
{"translate":"plugin.sword"}
plugin test language
```

**actual**
```
[o] plugin test language
[x] plugin.sword # wrong!
[o] {"translate":"plugin.sword"}
[x] plugin.sword # wrong!, but expected, since sponge does not provide abilities to register own translation
```

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 7) of SpongeAPI. Support for API 7 ended in January 2022.

API-7 is now end-of-life. We will not be issuing any more API updates for version 7 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API7/1.12.2[^2]
___

The Text API is now supplied by the [Kyori Adventure library](https://github.com/KyoriPowered/adventure/) so this issue is no longer relevant to this repository.

[^1]: https://forums.spongepowered.org/t/status-update-8th-january-2022-spongeapi-8-released/39861#minecraft-1122-spongeapi-7-10
[^2]: https://forums.spongepowered.org/t/sponge-status-update-28th-may-2022/40135#api-71122-community-support-8
