### ISSUE TITLE
Use LinkedHashSets for Set serialization in configs

### ISSUE THREAD

**Issue by ST-DDT** [SpongePowered/Sponge#2100]
The `TypeSerializer` for `Set`s currently uses a plain `HashSet` as an implementation, however this is confusing/frustrating for server owners, because they might put some logic  into their entries.
It would be nice if we could switch to a `LinkedHashSet`, similar to the `MapSerializer` that is provided by Configurate which explicitly uses a `LinkedHashMap` to retain the order.
Internally the `SetSerializer` uses a `ArrayList` for serialization so there aren't any obstacles for implementation either.

### Example-Config

````groovy
bannedBlocks: [
  "minecraft:stone",
  "minecraft:stone_stairs",
  "minecraft:stone_slabs",
  "minecraft:wood",
  "minecraft:wood_stairs",
  "minecraft:wood_slabs"
]
````

### Code-Refs

**`SetSerializer`**

https://github.com/SpongePowered/SpongeCommon/blob/6e2c2b2163c9f6474611bd4f994a510f1f5bea7f/src/main/java/org/spongepowered/common/util/SetSerializer.java#L41-L43

**`MapSerializer`**

https://github.com/SpongePowered/configurate/blob/367b2044ffd953a1cb8795c0b5ea0273a64bc09a/configurate-core/src/main/java/ninja/leaping/configurate/objectmapping/serialize/TypeSerializers.java#L173-L174

**Comment by ST-DDT** [comment]
Found while testing for https://github.com/SpongePowered/SpongeDocs/pull/766

**Comment by ryantheleach** [comment]
Not sure if related, since sets are values in hocon, but just in case:

Upstream Hocon:
https://github.com/lightbend/config/issues/365
https://github.com/lightbend/config/issues/35


Add a set serializer to the default type serializers: https://github.com/SpongePowered/configurate/issues/89

Call to disable alphabetical order. : https://github.com/SpongePowered/configurate/issues/31
