### ISSUE TITLE
ChangeBlockEvent.Pre fires on chest open

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/Sponge#2118]
This issue was originally submitted by @Shmeeb in [SpongePowered/SpongeAPI#1918](https://github.com/SpongePowered/SpongeAPI/issues/1918).
___
Minecraft: 1.12.2
    SpongeAPI: 7.1.0-ff990df
    SpongeForge: 1.12.2-2705-7.1.0-BETA-3477
    Minecraft Forge: 14.23.4.2705

**Comment by ImMorpheus** [comment]
Cannot reproduce.
`
ChangeBlockEvent.Break.Pre` does not exist.
I'm assuming you mean `ChangeBlockEvent.Break` which is not fired for me when opening a chest.

**Comment by Faithcaio** [comment]
Maybe it's just `.Pre` ? I remember having a similar issue with opening chests.
Should it even fire any ChangeBlockEvent when opening a chest?

**Comment by Shmeeb** [comment]
``
    @Listener
    public void onBreak(ChangeBlockEvent.Break.Pre e, @First Player player) {
``

definitely exists in 7.1.0

**Comment by dualspiral** [comment]
So does `ChangeBlockEvent.Break.Decay.Place.Break.Break.Break.Post.Pre`, thanks to how Java handles inheritance and nested interfaces - it's just an alias for `ChangeBlockEvent.Pre` (it becomes `org.spongepowered.api.event.block.ChangeBlockEvent$Pre` in the bytecode).

The interfaces `ChangeBlockEvent.Break.Pre` and `ChangeBlockEvent.Pre` are the same, the former becomes the latter in this case. `ChangeBlockEvent.Break.Pre` and `ChangeBlockEvent.Break` are not the same - the `Break` part of the event is irrelavent.

@Shmeeb because your issue has little to go on, I don't know what you are trying to indicate, whether the "break" or generally firing on a chest open was a problem. If you were flagging up a `Break` event was occuring when a chest was opened, it's just Java inheritance that is causing confusion.  This is a `Pre` event, not a `Break` event, no matter the signature. 

Can you confirm what you think is wrong?

**Comment by Shmeeb** [comment]
I didn't think it was intended for a BlockBreakEvent of any kind to be fired when I open a chest, which is why I filed the issue.

**Comment by gabizou** [comment]
It's intended to have the `ChangeBlockEvent.Pre` fire here because of the pending block state change of the chest that will take place within the same tick in the world. There are several block states that exist even for chests, and the fact that you're opening it, changes that state.

This is working as intended.
