### ISSUE TITLE
bounding box restrictions

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [SpongePowered/Sponge#2122]
I am trying to troubleshoot bounding box restrictions Minecraft Cauldron/kCauldron

**Comment by dualspiral** [comment]
We're not Cauldron or any derivative thereof. We do not provide support for anything but Sponge. Nor could we help anyway, because you've provided next to no information about what your problem is.

If you need help with **Sponge**, please visit us on our forums, IRC or Discord as they are more appropriate places for support. Cauldron is dead, if you need support for any Cauldron derivative, please go ask the maintainers of that project.
