### ISSUE TITLE
Issue with custom data.

### ISSUE THREAD

**Issue by teitss** [SpongePowered/Sponge#2140]
**I am currently running**
- SpongeForge version: RB 7.1.4
- SpongeVanilla version: -
- Java version: 8
- Operating System: Debian 9

- Plugins/Mods: spongeforge, pixelmon, economylite, luckperms, pixelmoney, uniquecosmetics

**Issue Description**
After updated my server to SpongeForge RB  7.1.4, some players are throwing exceptions when trying to login. Before SpongeForge RB 7.1.4 I was running SpongeForge 3392.

**Stack trace**
https://gist.github.com/teitss/f0607af91cd5aa57217578377277aad0

**Comment by gabizou** [comment]
Your plugin needs to register keys during the event. The problem here is that the server has long since started and keys are only being constructed then, when they should be constructed during the registration event.

I'm leaving the issue open because we can improve the error handling and message to make this clearer for others in the future.

**Comment by teitss** [comment]
Alright, now I'm registering my data and keys during correct events, it's working fine, ty
