### ISSUE TITLE
InventoryClickEvent OffHand SlotINdex/EquipmentType Property Inconsistent Retrieval Issue

### ISSUE THREAD

**Issue by nihiluis** [SpongePowered/Sponge#2150]
**I am currently running**

    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-7105dfc
    SpongeForge: 1.12.2-2705-7.1.0-BETA-3361
    Minecraft Forge: 14.23.4.2705

- Java version:  8
- Operating System: archie linux

- Plugins/Mods:
i only use prviate mod + nuclear and lucksperms

**Issue Description**
im using InventoryClickEvent in code. i want to check which item you put in a specific slot. this works ok. i use shift click on say helmet and I get the proper slotindex where the helmet is really located. if i rely on equipmentslot instead, it works great as well (while using shiftclick). but now comes the bug. I now click shift click on my off hand and then I get the slotindex and equipmenttype from where the item will be located after the click. this behaviour is inconsistent (for other slots I geet the slotindex from where it is actually located when i click on the item) and incomprehensible for me. i have made 2 images which can maybe help your comprehension of the error.

is this logic error by me or bug of spongebob?

```kotlin
    @Listener
    @Include(ClickInventoryEvent.Primary::class, ClickInventoryEvent.Drop::class)
    fun onInventoryClick(event: ClickInventoryEvent) {
        val slotTx = (if (event.cursorTransaction is SlotTransaction) {
            event.cursorTransaction as SlotTransaction
        } else {
            if (event.transactions.size > 0) {
                event.transactions[0]
            } else null
        }) ?: return

        val isPickUp = slotTx.original.type != ItemTypes.AIR

        val stack = (if (isPickUp) slotTx.original else slotTx.default).createStack()

        println("Trying to find eq with EquippableID ")
        val eq = Equippables[stack] ?: return
        println("Eq found with id " + eq.id)
        val player = event.cause.first(Player::class.java).orElse(null) ?: return

        val equipmentSlot = slotTx.slot.getInventoryProperty(EquipmentSlotType::class.java).orElse(null)
        var slotIndexValue = slotTx.slot.getInventoryProperty(SlotIndex::class.java).orElse(null)?.value
        println("Found equippable " + eq.id + " on SlotIndex " + slotIndexValue)

        val isBauble = RpgBridge.isBaublesContainer(event.targetInventory)
        println("Found equipment Slot ${equipmentSlot?.value}")

        if (equipmentSlot?.value == EquipmentTypes.OFF_HAND) {
            println("It is on off hand")
            slotIndexValue = if (isBauble) 52 else 45
        }
        val foundSlot = if (isBauble && eq.onBaubleSlots != null)
            eq.onBaubleSlots!!.find { it.value == slotIndexValue } else
            eq.onSlots.find { it.value == slotIndexValue }
        if (foundSlot != null) {
            val isDjinn = RpgBridge.isDjinnContainer(event.targetInventory)

            if (eq.isExtraRpgItem && !(isBauble || isDjinn)) {
                return
            }

            if (!isPickUp) {
                eq.onEquip(player, stack)
            } else if (isPickUp) {
                eq.onUnequip(player, stack)
            }
        }
    }
```

**Comment by gabizou** [comment]
No clue what SpongeForge 1427 means....

**Comment by nihiluis** [comment]
sorry this is it:

    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-7105dfc
    SpongeForge: 1.12.2-2705-7.1.0-BETA-3361
    Minecraft Forge: 14.23.4.2705

**Comment by ryantheleach** [comment]
I'm having difficulty understanding the images / hand writing, and your code is in Kotlin, which while unfamiliar I can **attempt** to read with some difficulty, So can you confirm the following:

Do you mean to say,

During a ClickInventoryEvent (ClickInventoryEvent.Primary and ClickInventoryEvent.Drop specifically), you can get the slot number by (getting the cursorSlot transaction, or the first transaction) 

and calling

slotTx.slot.getInventoryProperty(SlotIndex::class.java).orElse(null)?.value

In order to get the SlotIndex.

(Which you then hard code replace with 45 (or 52 if baubles is installed) to work around this bug)

Shift clicking on an armor slot, gives you the slot number of the slot the item was occupying before the event.

Where as Shift clicking on an offhand slot, gives you the slot number of the slot the item was occupying, should the event succeed?

---

It seems to me that you are making the assumption, that the first slot index, or the cursor transaction (Which in the current API, I'm not sure is (ever) a Slot transaction, but I could be wrong) is the slot that is clicked. 

Is this documented behavior?

Whilst it's strange that the order is inconsistent, I'm not sure that the order could, or should be relied upon to work out what interaction the user made to trigger this event. (If this is indeed your usecase / intention)

What end result are you hoping for? / Why are you writing this listener in the first place? You may have an [XY problem](http://xyproblem.info/) that is better solved in Sponge by a different method, or introducing different API.

**Comment by Faithcaio** [comment]
The cursor transaction is in fact **never** a SlotTransaction.

**Comment by ryantheleach** [comment]
@Faithcaio 

```

        @Listener
        @Include({ClickInventoryEvent.Primary.class, ClickInventoryEvent.Drop.class})
        public void onShiftClick(ClickInventoryEvent event, @First Player player) {
            List<SlotTransaction> txs = event.getTransactions();
            Transaction<ItemStackSnapshot> cursorTx = event.getCursorTransaction();
            SlotTransaction cursorSlotTx = cursorTx instanceof SlotTransaction ? (SlotTransaction) cursorTx : null;

            Stream<SlotTransaction> slotStream = Stream.concat(Stream.of(cursorSlotTx), txs.stream()).filter(Objects::nonNull);

            String resultString = slotStream
                    .map(slotTx -> slotTx.getSlot().getInventoryProperty(SlotIndex.class))
                    .map(s -> optToString(s, slotIndex -> slotIndex.getKey() + ":" + slotIndex.getValue()))
                    .collect(Collectors.joining(", "));


            player.sendMessage(Text.of("SlotIndexes : " + resultString));
        }

        private <T> String optToString(Optional<T> opt, Function<T, String> toString) {
            return opt.map(toString).orElse("none");
        }
```

Testing with this, does indeed show that the order of the transactions is inconsistent for the offhand slot.

**Comment by Faithcaio** [comment]
The SlotTransactions are (maybe always, there may be exeptions for events that do not deal with Containers) ordered by SlotIndex.
Thats because when creating the Transaction I go in that same order.
I'd call that pretty consistent.

**Comment by nihiluis** [comment]
```
What end result are you hoping for? / Why are you writing this listener in the first place? You may have an XY problem that is better solved in Sponge by a different method, or introducing different API.
```

I want to listen/call callbacks when a certain slot in my inventory is clicked on with a specific item. At the same time I want it to be the same system for multiple (also modded) inventories.

I don't know of anything that is more comfortable than passing a certain SlotIndex.

```
The SlotTransactions are (maybe always, there may be exeptions for events that do not deal with Containers) ordered by SlotIndex.
Thats because when creating the Transaction I go in that same order.
I'd call that pretty consistent.
```
hmm, makes sense, thank you
