### ISSUE TITLE
Fix needed for chunk savestate dupe glitch

### ISSUE THREAD

**Issue by tenten8401** [SpongePowered/Sponge#2156]
**I am currently running**
- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-4f54ce0d
- Sponge: 1.12.2-7.1.5-SNAPSHOT
- SpongeForge: 1.12.2-2768-7.1.5-RC3506
- Minecraft Forge: 14.23.5.2768

**Issue Description**
There's apparently a dupe bug in vanilla minecraft that needs to be fixed, I don't know if there's an issue for it already but I couldn't seem to find one. It allows the player to prevent a chunk from saving, that way when they unload & load the chunks, it reverts back to the old state.
https://youtu.be/uw7vEGhKoH8?t=100

Paper Spigot has a patch for it already that basically just tries to check the book size and kicks the player off if it's too large.
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0403-Book-Size-Limits.patch

**Comment by randombyte-developer** [comment]
Updated link: https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0403-Book-Size-Limits.patch

**Comment by gabizou** [comment]
Someone can write a PR for this.

**Comment by Shybella** [comment]
I tested this dupe at one point and wasn't successful. Have you attempted this?

**Comment by tenten8401** [comment]
@Shybella I had some players successfully do it on my Spongeforge server.

**Comment by zand** [comment]
I don't think https://github.com/SpongePowered/SpongeCommon/commit/0f8df35e74e1e1cce7974220e8c5e1df68acd9fa fixes the problem describe in the video as they state its due to compressed chunks being limited to 1MB in size. They discuss different ways they thought of to trigger the bug starting with "shulker boxes" and only did it with books because it seemed the easiest.

A proper fix would be to get rid of that limit by doing something like saving over sized chunks to a separate file until it gets fixed in vanilla.

**Comment by zand** [comment]
A video popped up of players abusing this bug without books https://youtu.be/-xDODejcM6c

**Comment by Aaron1011** [comment]
@zand: A full fix can be found in the latest Forge build.
