### ISSUE TITLE
Broken static colored Text instances

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/Sponge#216]
It seems that whenever you build a static Text instance with a color, like the following:

``` java
private static final Text MY_TEXT = Texts.of(TextColors.RED, "My red text!");
```
the TextColor is interpreted as null somewhere, and so when the Text is sent to a player, they would see: `nullMy red text!` (uncolored).

**Comment by simon816** [comment]
This happens because the field is initialized before the sponge implementation sets the values in the enum classes.
The problem is always true if the constant field is declared in the class with `@Plugin` on it.

As a test, I created a class called `Constants` with that field.
In the plugin class, I subscribed to `PlayerJoinEvent` and called
`event.getPlayer().sendMessage(Constants.MY_TEXT);`
The message on the client was correctly displayed in red.

After a few more tests, it appears that the enum-style field `TextColors.RED` is only available from `GameState.INITIALIZATION` (`InitializationEvent`) onwards.
This makes sense because the field is set in the `init` phase in [`SpongeGameRegistry`](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/registry/SpongeGameRegistry.java#L2099)

In order to fix the issue, I had to subscribe to the `FMLConstructionEvent` in `SpongeMod` and call `setTextColors()` at that point. Other enum-style classes are likely affected by this issue.

**Comment by Minecrell** [comment]
@simon816 Yes, this is a known problem.

**Comment by Zidane** [comment]
@SpongePowered/developers 

Someone re-create this issue in common as it is a registry problem.

**Comment by RobertHerhold** [comment]
Closing this, and I recreated the issue: SpongePowered/SpongeCommon#6
