### ISSUE TITLE
Inventory Archetype in CraftItemEvent.Preview is always UNKNOWN

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/Sponge#2173]
**I am currently running**
- SpongeVanilla version: 1.12.2-7.1.5-RC145

**Issue Description**
When getting the inventory archetype from the inventory invovled in a CraftItemEvent.Preview, the archtype is always returned as Unknown.

```java
    @Listener
    public void onItemCraft(CraftItemEvent.Preview event, @First Player player, @Getter("getPreview") SlotTransaction preview, @Getter("getCraftingInventory") CraftingInventory inventory) {
            inventory.getArchetype() // This is always UNKNOWN
        }
    }
```

**Comment by Faithcaio** [comment]
If you call `getArchetype()` on `getTargetInventory()` it works.
For `getCraftingInventory` it returns unknown because it is not actually a real inventory but only an Adapter provided by Sponge.

The whole InventoryArchetype thing is not really fully implemented. 
Only works for creating custom inventories and the base vanilla inventories/containers we mixin into.
