### ISSUE TITLE
Modify incorrectly firing for trees generated via bonemeal

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Sponge#2209]
Right now when a tree is generated by a Player with bonemeal, the PhaseTracker is incorrectly firing a Modify when it shouldn't.

Chain of events:

- Break (Sapling is broken)
- Modify (Transactions seem to only have the leaf states and not the log states)
- Place (Transactions include both leaf and log states)

**Comment by gabizou** [comment]
Current chain of events:
- Place (Transaction includes sapling being replaced with log and intermediary changes such as sapling to air, then air to log).
- Post (containing place)

Debugging screenshot:
![sapling transaction](https://i.imgur.com/bK9af42.png)

Intermediary transactions:
![intermediary](https://i.imgur.com/8V7he4F.png)

Should be fixed now (since Break was a side effect of the sapling being turned into air, and processed as it's own transaction at that point).
