### ISSUE TITLE
Canceling ChangeBlockEvent.Place Stack Issues

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Sponge#2242]
@ImMorpheus 

When canceling ChangeBlockEvent.Place and you used a carrot (basically planting the carrot), it does stop the carrot from being placed but eats one of the carrot's stack in the inventory.

**Comment by Zidane** [comment]
@ImMorpheus Status?

**Comment by johnfriedrich** [comment]
Tested that a bit more with clean SpongeForge 3728 with just GP 689 and Luckperms. The issue seems only apply to the mentioned ChangeBlockEvent.Place. For example, Blocks are not being eaten when placing them into itemframes even if its canceled.
Blocks are just goneclientside but in some claimconfigurationsin GP, they disappear completeley. But guess thats fixed anyway if the underlying issue is fixed
