### ISSUE TITLE
Add regression tests for strange issues

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Sponge#2256]
Now that McTester support has been merged into SpongeForge, it would be nice to write regression ticks for some of the weirder issues we've encountered.

Some ideas:

- [ ] Furance item dropping (https://github.com/SpongePowered/SpongeForge/issues/2725)
- [ ] 'Recursive' redstone sticky pistons
- [ ] Anything to do with advancements

**Comment by gabizou** [comment]
Another is to add the 0-tick piston mechanism. It's a little complicated since it requires logging and tracking the *exact* `BlockTransaction`s that would be submitted, comparing their proxy information, and then successively validating that they abide by the same `BlockTransaction`s that otherwise would be created with vanilla (basically, I already have some minor logging of said transactions for a 0-tick piston machine) to validate that each `BlockState` and `TileEntity` exists in the correct position, between processes.
