### ISSUE TITLE
Sand, gravel, anvils, etc, disappear instead of falling

### ISSUE THREAD

**Issue by VcSaJen** [SpongePowered/Sponge#2263]
**I am currently running**

- SpongeForge version: 1.12.2-2825-7.1.6-RC3708
- SpongeVanilla version: 1.12.2-7.1.6-RC175

**Issue Description**
When sand, red sand, gravel, concrete powder, anvils, etc. are affected by gravity (i.e. there's air underneath them), they disappear instead of falling. All Sponge settings are default settings, no mods or plugins.

**Logs**
There's nothing in the logs.

**Note**
According to [this comment](/SpongePowered/SpongeCommon/issues/2228#issuecomment-478404439), the issue should have been fixed in 2fccd57, yet issue is still present.

**Comment by phit** [comment]
please retest on 3711, i wasn't able to reproduce this

**Comment by VcSaJen** [comment]
@phit Tested again on SpongeForge 1.12.2-2825-7.1.6-RC3713 and SpongeVanilla 1.12.2-7.1.6-RC180, still same.
<blockquote>i wasn't able to reproduce this</blockquote>Are you sure you tested this on clean install with no mods or plugins?

Video:
https://www.youtube.com/watch?v=xR0tqE6OXY8

**Comment by phit** [comment]
> Are you sure you tested this on clean install with no mods or plugins? 

yep, however I just figured out the issue, similarly to https://github.com/SpongePowered/SpongeForge/issues/2731 this is only broken if there's no even listeners

as a workaround for now you can add `-Dsponge.shouldFireAll=true` to your java arguments

**Comment by gabizou** [comment]
Found the root of the issue: Since the `ShouldFire` flags are off with no listeners, the [code I wrote at some point last year to fix some other issue](https://github.com/SpongePowered/SpongeCommon/commit/d27527a5c0e8c7dab6df65cca12a679b789e0ad2) didn't take into consideration the possibility of no captures. I'm assuming this is because at that point, we didn't have the `ShouldFire` for any block changes. Doing a full audit now and will re-test this issue and the previous issue that that commit was aiming to fix (though, I don't know how it aimed to fix it.... it seems odd to be calling to set the block to air twice...)
