### ISSUE TITLE
java.lang.AbstractMethodError EntityArmorStand Exception

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/Sponge#2276]
**I am currently running**

- SpongeForge version: 3745
- SpongeVanilla version: null
- Java version: 201
- Operating System: Win Server 2016

- Plugins/Mods:

**Issue Description**

Log: https://pastebin.com/raw/BVsJNX3g

Reproduce with HuskyCrates-v2.0.0-PRE9H2-API7 and HuskyUI-v0.6.0-PRE3-API7. 

Mods/Plugins: https://pastebin.com/raw/QVBKZm3A

**Comment by gabizou** [comment]
@ImMorpheus one thing your PR could not have tested was an obfuscated environment. Need to explicitly implement the methods you added to `IUserOrEntity`. It's a erason why we try to make our methods not soft overridden by the target classes because they'll end up working in development, but not in production.

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/commit/5c1d3a2005c62c47546cde94ade3ef2316d1fc37

**Comment by Shybella** [comment]
Confirmed, resolved now.
