### ISSUE TITLE
Diagnosing level_sponge.dat corruption

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/Sponge#2328]
I've seen quite a few issues relating to occasional corruption of the `level_sponge.dat` files. Diagnosing these issues seems to be extremely hard since the actual corruption only happens once. Whenever someone does get a corruption issue, we never see the actual corruption, only the crashes caused by the broken file. While deleting `level_sponge.dat` and replacing it with `level_sponge.dat_old` is a decent workaround, I think we ought to fix the issue of the corruption itself. Any thoughts on how we could diagnose this?

**Comment by phit** [comment]
i think for some reason the file is always held open? as i frequently see people having this file as the only file being corrupted during a loss of power

if possible it should be changed to be only be opened and closed during level saving

**Comment by JBYoshi** [comment]
It doesn't seem to be held open. Sponge uses a try-with-resources statement to close the stream as soon as it's done writing. While it is held open while preparing the NBT data, I tested throwing an exception in there and it just creates an empty `level_sponge.dat_new` file.

https://github.com/SpongePowered/SpongeCommon/blob/9db3957ac468a3ceed864c490da2f33e9064ae8e/src/main/java/org/spongepowered/common/mixin/core/world/storage/SaveHandlerMixin.java#L127-L129

**Comment by dualspiral** [comment]
Looking at the code, it might not actually be a problem with the file saving routine itself, there is a chance we _might_ be passing an empty NBT compound to the save routine. If that's the case, it's likely this is the reason the "old" files are also zero length, which I also see a lot.

I'm going to add a commit that does the following:

* Prints an error to the console if the provided NBT compound is empty, then bails out of saving, leaving the current file intact (there are times it could be empty, we shouldn't be saving anyway in that case)
* Prints an error to the console if the saved file is zero length, then removes the new file, leaving the current file intact (this should never happen, of course, so it makes sense to have a warning and not overwrite the file in this scenario)

That should give an indication as to what is failing, and also keep some sanity around the level files. Once we know which scenario it is, we can then take a stab at fixing it. We can always reduce the verbosity of the errors once we know what is going on.

**Comment by ImMorpheus** [comment]
Closing this. There have been no reports of corruption issue and dual's code was pushed to stable.

**Comment by dualspiral** [comment]
Just as it gets closed, I'm getting a report of this happening to both `level.dat` and `level_sponge.dat`. I am in the process of trying to get logs to figure out what is going on, but it is clear there is a separate issue going on, especially if `level.dat` is zero length.

Re-opening to keep this on the radar. I'll attach any logs I get that may have clues.

**Comment by Shybella** [comment]
I've only experienced broken level_sponge if you have a server running then power down the whole machine unexpectedly. (pulling the plug, hw fault, etc).

**Comment by dualspiral** [comment]
Be that as it may, as we have it set up, the file write should not last long, that is, we shouldn’t be holding it open for more than a couple of hundred microseconds every minute or two, depending on save frequency. The frequency that we’re receiving reports of corrupt dat files, indicates to me that there is something holding the file open, perhaps not writing to it properly or completely. What’s more concerning than that is that we write to a temporary file first, then move it over - that move should be lightning fast. So, there is still something amiss here.

I did a quick check with a recent stock SF build and investigated which threads accessed the save, thinking it might be a race condition. It was always the server thread, but you never know if mods try to issue saves off thread - possible I guess, we just don’t have this information - one to keep in mind.

Another thing I noticed is how we handle restoring the backed up file in case of failure. We actually don’t - if we detect a `level_sponge.dat` file and it’s corrupted, we just throw an exception, no attempt is made to read the “old” file. There is then the danger that the current file gets backed up over the old file during the startup sequence, destroying the backup before it can even be used.

I have a branch that will mean that the backed up file will be used if the standard file is corrupt. Further, the corrupted file will be renamed so that it is kept around - allowing for inspection later on. I will turn it into a PR soon and look at getting it in very quickly so we can at least have a look at the corrupted files and see if it provides any clues.

**Comment by BraINstinct0** [comment]
> I've only experienced broken level_sponge if you have a server running then power down the whole machine unexpectedly. (pulling the plug, hw fault, etc).

Experienced this just yeterday. However, since I was using a script to automatically re-start the server, it just overwrote the corrupted level_sponge.dat_old with the corrupted one. No ways of recovery...

**Comment by dualspiral** [comment]
Sponge version, logs showing the corruption? If you're not on 7.1.8 or later, then you need to update. If you have a later version, Sponge will tell you that it tried to load from a backup and what it has done with the corrupted file - in which case please zip it up and attach it here.

**Comment by dualspiral** [comment]
I'm going to close this now. Since I added my changes, I've seen virtually no complaints about this. It isn't a fix in the truest sense of the word, but it now uses the backup correctly and we can ask for corrupted files when people come up with this again.

**Comment by JBYoshi** [comment]
This has happened again, and we now have a copy of the corrupted file: https://discordapp.com/channels/142425412096491520/142425412096491520/690578287789080626

**Comment by dualspiral** [comment]
I'm closing this as I've done a fair amount in trying to mitigate this. We'll make changes as more information becomes available.
