### ISSUE TITLE
Mixin Injection Failure on Startup for SpongeVanilla

### ISSUE THREAD

**Issue by WillBAnders** [SpongePowered/Sponge#2338]
**I am currently running**
- SpongeVanilla version: 1.12.2-7.1.7-RC246
- Java version: 1.8.0_212
- Operating System: Windows 10

**Issue Description**
Crashes from critical injection failure on startup with fresh server prior to reaching the EULA. This issue  was introduced in RC246 and still present in RC251 - both logs have been included below.

I am reporting this in Common as it seems the cause is [this method in WorldMixin](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/core/world/WorldMixin.java#L859-L863) which was introduced to SV in RC246.

[SV-RC246 Startup Logs](https://gist.github.com/WillBAnders/81f8cade197a2cd2b49f75a264da5300)
[SV-RC251 Startup Logs](https://gist.github.com/WillBAnders/b4fa29cd4f4194c18b53d6eee56d5e62)

**Comment by gabizou** [comment]
The first startup issue introduced in RC246 is already fixed [in this commit](https://github.com/SpongePowered/SpongeCommon/commit/9c89ec380686e12e43fb8afc52c3d874d1c7a4cb). The second issue of 251 is odd as I've not been able to run into that issue before, but is valid to be fixed in a separate issue.
