### ISSUE TITLE
ArchetypeVolume: The box is degenerate on y

### ISSUE THREAD

**Issue by AlexandreGerault** [SpongePowered/Sponge#2361]
**I am currently running**

- SpongeVanilla version: 1.12.2-7.1.6
- Java version: openjdk version "1.8.0_222"
- Operating System: Ubuntu 19.04
- Plugins/Mods:
My BattleRoyale plugin

**Issue Description**
When I select two positions on the same Y coordinate and then enter the command `/brp copy` I get an error saying `The box is degenerate on y` (log attached)

Here is the error log: https://gist.github.com/AlexandreGerault/fcfa434d78ce15e870f35ef58efa7192#file-error-log
Here is the Command code: https://gist.github.com/AlexandreGerault/fcfa434d78ce15e870f35ef58efa7192
Here is a working version of the command (thanks to @pie-flavor): https://gist.github.com/AlexandreGerault/fcfa434d78ce15e870f35ef58efa7192#file-solved-by-pie_flavor-copyselectioncommand-java

**Comment by dualspiral** [comment]
There isn't a bug here, what you're doing is wrong.

The error message is not clear to most people as it is mathematical terminology. It means your selection has at least one side length of zero - in your case, Y. That method is not actually using block positions as the parameters, it's using actual positions - but by using `Vector3i`, that is, integer co-ordinates, we're guaranteeing ourselves that we can only select vertices, or corners, of the blocks.

Say I wanted to create a 1x1x1 volume of the block with **block position** of (0, 64, 0). The actual volume goes from (0.0, 64.0, 0.0) to (1.0, 65.0, 1.0), so that is my min and max co-ordinate corners of that block. If I want blocks from (17, 64, 240) to (24, 64, 310) inclusive, I need (17, 64, 240) as the min corner, and (25, 65, 311) as the max corner.

So the code is right in what it's doing - you are getting a degenerate box - a 2D area that has no blocks in! You need to think in terms of actual position, not block position.

(edits to fix typos)
