### ISSUE TITLE
Another bug with CraftItemEvent

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/Sponge#2363]
**I am currently running**

- SpongeVanilla version: 7.1.6 and also 7.1.7-RC272
- Java version: OpenJDK 1.8.0_222
- Operating System: Kubuntu 18.04
- Plugins/Mods: None

**Issue Description**

`CraftItemEvent` allows to craft items with forbidden components, this is difficult to achieve, but as you can see on the video, it’s possible. Moreover, items can be crafted cheaper than the original craft, due to the fact that the result of crafting hangs in its slot.

It seems that the [previous issue](https://github.com/SpongePowered/SpongeCommon/issues/2097) was either not completely fixed, or something was broken again.

Video demonstration: https://www.youtube.com/watch?v=bDho0Vtx5uk

Source code of the listener:

```java
@Listener
public void onCraftItem(CraftItemEvent event) {
    Objects.requireNonNull(event, "event");
    
    for (Inventory slotInventory: event.getCraftingInventory().slots()) {
        Optional<ItemStack> itemStackBox = slotInventory.peek();
        
        if (itemStackBox.isPresent()) {
            if (itemStackBox.get().getType().equals(ItemTypes.STICK)) {
                event.setCancelled(true);
            }
        }
    }
}
```

**Comment by JBYoshi** [comment]
After looking at this, I think there are a few really confusing parts with the crafting events.

- I noticed that `CraftItemEvent` extends `ChangeSlotEvent`, which makes the cancel behavior a bit ambiguous. If the event is cancelled, should it prevent any output from appearing, or should it prevent the output from changing?
- With `CraftItemEvent.Craft`, the inventory slots have already been cleared by the time the event gets called. I assume the original contents would be in the transaction list, but it's not obvious that this is where they are. Because the plugin checks the crafting inventory slots instead of the transactions, the actual `CraftItemEvent.Craft` is never cancelled.

**Comment by Lignium** [comment]
@bloodmc Partially the problem is solved, only partially. I still can't completely restrict crafting. In order not to record a video I will write in words:

The test code is the same. The task is to limit crafts in which used sticks. For example, take the craft of a stone pickaxe. If you put cobblestones in the top row, we will have stone slabs in the output slot, which is logical. But if you additional put sticks to get the recipe of stone pickaxe, there are still cobblestone slabs in the output slot. The result (cobblestone slabs) can be taken away, then all items will disappear from the crafting grid, along with our sticks.

![Screenshot_20200118_124015](https://user-images.githubusercontent.com/41531939/72662428-ae274e80-39ef-11ea-855f-63e08a85fc7f.png)

**Comment by ginyai** [comment]
It looks like set the final result to air is better than canceling the event, when handling `CraftItemEvent.Preview`.
