### ISSUE TITLE
Make source and destination IP and port permissions contexts

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/Sponge#239]
Adding these contexts gives a ton of additional flexibility for IP-based permission assignment. Say you wanted to give all users connecting from a certain IP all permissions (or whitelist by IP, or prevent anyone at your friend's house's IP from breaking cobblestone -- possibilities are endless). Simply assign a permission or parent based on context.

The contexts created by this would be:

Context    |  Contents
------------- | --------------------------------------------------
`srcip`       |  The source IP address of the player
`srcport`   | The source port of the player
`destip`    | The destination IP address (the IP on the server that the initial connection was directed to)
`destport` | The destination port

However, the existing context system presents issues if we attempt to bring in IP range matching (CIDR) into the mix, which is convenient in a lot of cases. There are a few ways this could be resolved though:

1. The simplest, don't allow IP ranges. This means that each IP mapping maps to one port and easily works within the context system.
2. Have a registry of IP ranges (maybe by getting all contexts for all players -- or all values -- could require API additions), and add all matching values to subject. This would be a bit complicated to implement and could easily get out of sync. However, it mostly preserves the ideas that contexts are simple key-value mappings. 
3. Have named ipsets configured in the Sponge configuration. These would then be available to use as values for an ipset? context. This could be in addition to single ip matches. I feel like this would be the easiest to implement, but this is also not at all seamless.
3. Redesign the context system to have context objects perform logic -- be more predicates than simple key->value mappings. This requires the most changes (and changes core ideas of the permissions api) and could also cause performance issues, so I don't really think this is the way to go.

**Comment by Mumfrey** [comment]
Also CIDR subnet notation maybe?

**Comment by zml2008** [comment]
yeah, that's what I'm thinking of to specify ranges. I just don't want to give every player 256 or 64 contexts (2*length of ip) if I have to specify them statically, cuz that would end up being super slow.

**Comment by ST-DDT** [comment]
I guess srcPort is hard to use because it is (mostly) chosen at random.
Unless im mistaken you dont have to add every single ip in from an ip range to the players context only the entire range object. And since these are calculated on join i dont see any issues here.

IMO this should work without configuration in the sponge config.
Because the permission plugin's config should deal with it all alone.

**Comment by zml2008** [comment]
for a given ipv4 address there are 32 ranges that match it. for a given ipv6 address there are 128 ranges that match it. (both following CIDR syntax). how do we know which ones are in use as contexts?

**Comment by ST-DDT** [comment]
The permission service or the context calculator alone are able to attach contexts to a subject.
The service/calculator may choose to add an ip context that does not match the clients one for whatever reason. IMO it is not the APIs goal to verify which contexts are set. Only to provide a list of usefull values. This ensures that only useful CIDRs get applied.

Contexts are identified by their type `IPv4Source` and their name `10.42.0.0/19`. When getting the list of active contexts from the subject noone should do anything with that name because it is just a name.
The name could be `local` or `private` as well.

The only thing we could do is adding a field or method (to the service?) to register/get used CIDR entries as a bridge between service and calculator. To avoid dependencies between them. If we use a sponge config we have a dependency between the config and the service. This could lead to useless cidrs beeing added or or required cidrs being missing.
Only the permission service can tell use which CIDRs it is listening for. Thats why i suggested adding the getter to the service.

**Comment by Zidane** [comment]
@zml2008 

Move this up to common.

**Comment by Phroa** [comment]
Oh man, I would love to be able to ensure that my staff members had to join from their IP range, preventing acct. theft and all that. :+1:

**Comment by ryantheleach** [comment]
A better idea is to use the classic hostname security model that sk89q documented. That way instead of setting up a separate permission for each of your staff members, just have a differing hostname per staff rank that they need to connect to.

Even better, they can easily demote themselves by connecting to the normal server, allowing them to play as regular players unless they want to swap into "mod mode"

**Comment by zml2008** [comment]
yeah ryantheleach, that setup would work here too. I'll add a virtualhost context as well which has the connected hostname.

**Comment by ryantheleach** [comment]
Oh cool, I stupidly assumed that's what the destinationIP was used for.

**Comment by Phroa** [comment]
Actually, it is. (I presume anyway) it isn't the resolved hostname, but the actual destination IP.

**Comment by Zidane** [comment]
@zml2008 

Is this still an issue?
