### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by ghost** [SpongePowered/Sponge#2428]
**I am currently running**
- SpongeForge version: 7.1.7
- Forge version: 2838
- Java version: Java 8
- Operating System : Ubuntu
- Plugins/Mods:
[BungeeGuard  ](https://github.com/lucko/BungeeGuard) A ported version, but works fine

[BungeeGuard ported version link](https://cdn.discordapp.com/attachments/629641779406307348/630792941551747088/BungeeGuard-1.0-SNAPSHOT.jar)

**Issue Description**
I updated SF from 7.1.6 to 7.1.7, BungeeGuard does not work
This is the last working SF version 7.1.7-RC3866 , versions after 7.1.7-RC3866 will not work properly
I think it is 7.1.7-RC3868 that changed what caused the problem
maybe this is caused, not sure 
![image](https://user-images.githubusercontent.com/24543050/69766904-faef6580-11b4-11ea-8b54-9274c2a2cff4.png)

**Comment by dualspiral** [comment]
[spongeforge-1.12.2-2838-7.1.8-RC0.jar.zip](https://github.com/SpongePowered/SpongeCommon/files/3906014/spongeforge-1.12.2-2838-7.1.8-RC0.jar.zip)

@GranTesoro86 Can you try this build of SpongeForge for me with the version of the plugin you've provided? I've readded the user recreation step, if it was that, this should fix your problem. Please confirm before I merge this into Sponge proper.

@clienthax No point waiting for me, you really should be using `Auth` because that will have the game profile sent from the client, rather than accidently getting a cached version.

**Comment by ghost** [comment]
@dualspiral  oh yes, it worked

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/9a381922222664a996da4e6edbb76ba6d05ae025
