### ISSUE TITLE
Async tasks do not repeat after undefined time

### ISSUE THREAD

**Issue by LordRalex** [SpongePowered/Sponge#2482]
As of 7.1.7 (when scheduled tasks were touched to fix other async issues), other async tasks are getting stuck and failing to repeat.

It may not happen at the first iteration of it, however it eventually does stop executing. The test code below is a way to create and see that the task stops running.

Have not determined cause yet, but putting issue in for tracking.

```java
package test.threadtest;

import com.google.inject.Inject;
import org.slf4j.Logger;
import org.spongepowered.api.event.game.state.GameStartedServerEvent;
import org.spongepowered.api.event.Listener;
import org.spongepowered.api.plugin.Plugin;
import org.spongepowered.api.scheduler.Task;

import java.util.concurrent.*;

@Plugin(
        id = "threadtest",
        name = "Threadtest",
        description = "Test"
)
public class Threadtest {

    @Inject
    private Logger logger;

    @Listener
    public void onServerStart(GameStartedServerEvent event) {
        Task task = Task.builder().execute(() -> {
            logger.info("Time: " + System.currentTimeMillis());
        }).async().interval(3, TimeUnit.SECONDS).submit(this);
    }
}
```

**Comment by dualspiral** [comment]
This is a horrible bug with threading, but I think I've solved it. I'll push up a branch shortly before merging this, but my solution has three parts - one of which has come about because I actually read the javadocs this time. I'll explain in detail what is going on as I think it would be useful and interesting for people who work on threading (*ahem* _async phase tracker_[<sup>1</sup>](#f1)).

## I: Locks, Conditions and Threading Madness

In our loop, we make use of a `ReentrantLock` and an associated `Condition`. In my previous fix, I made the assumption that if I put a lock on a thread, it stops all other threads aquiring the lock.

This is a true assumption... **except** if a thread subsequently awaits a `Condition`. [From the `Condition#await` javadocs](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/Condition.html#await()):

> **The lock associated with this Condition is atomically released** and the current thread becomes disabled for thread scheduling purposes and lies dormant until one of four things happens:
>
>  *  Some other thread invokes the signal() method for this Condition and the current thread happens to be chosen as the thread to be awakened; or
>  *  Some other thread invokes the signalAll() method for this Condition; or
>  *  Some other thread interrupts the current thread, and interruption of thread suspension is supported; or
>  *  A "spurious wakeup" occurs. 
>
> In all cases, before this method can return the current thread must re-acquire the lock associated with this condition. **When the thread returns it is guaranteed to hold this lock.** 

In other words, awaiting a condition:

* Releases the lock
* Waits for the condition to be met
* Reaquires the lock when it becomes available

Why I didn't realise this before, I don't know - as we already made use of that fact in this system [<sup>2</sup>](#f2)). So, surrounding our signalling with a lock is a reasonable thing to do. As **nearly** all of our scheduler executor thread processing is surrounded by a locking mechanism, this will significantly reduce the amount of time available for there to be a race condition, where a signalling could occur when there is no awaiting. I believe that this was the largest issue and the simple solution of "read the docs and learn how to use these locks and conditions properly" is a lesson I can take away from this.

Threading is fun, huh?

## II: Keeping Track of State

Of course, above I said **nearly** all of our thread is covered by locks - but there is a non-zero amount that is not. So, we could aquire a lock before the executor thread itself aquires it, so it ends up waiting for a lock to release, and not awaiting on the condition. Not awaiting means that it'll reach the condition and wait. If there is one task, it may wait for `Long.MAX` nanoseconds which is a very long time - which is the source of the stalling.

Rather than introduce a complicated series of locks and conditions or blocking queues to try to catch every scenario, I've opted for a simple solution - use of an `AtomicBoolean` to indicate to the executor thread something has updated, and to instruct it to skip the next await if it isn't currently awaiting. We actually could probably use a standard `boolean` for this as the getting/setting is always done within the locks, but I've opted for an abundance of caution here.

This should cover the small chance of signalling when not awaiting.

## III: It's a little `volatile`

Finally, though this may not be strictly needed, the state of the task is now marked `volatile` to tell the JVM to not do any fancy thread caching with the task state as we will be accessing it from multiple threads, and potentially very quickly.

## Conclusion

I am going to PR this first and get it tested, but local testing seems to suggest this is solved. I'll push up a branch in a bit, if someone could compile and test that. It would be good to make sure it's not only working for me!

---
<a name="f1"></a><sup>1</sup> Don't worry @gabizou, I don't think this is going to affect any of the async phase tracker work! I'm sure that'll work first time without a hitch...

<a name="f2"></a><sup>2</sup> I had actually seen it, but didn't really question it, managing to convince myself it was okay. In hindsight, I really should have thought about the fact that [the condition was being signalled within that very same lock...](https://github.com/SpongePowered/SpongeCommon/blob/11a0398d9f3fe12ed7cf40ff758d6f7d36dbf154/src/main/java/org/spongepowered/common/scheduler/AsyncScheduler.java#L141-L149)

**Comment by dualspiral** [comment]
#2483 - if anyone wants to compile and test for me.
