### ISSUE TITLE
Please create a directory to contain plugins

### ISSUE THREAD

**Issue by KieronWiltshire** [SpongePowered/Sponge#252]
I think there should be a folder called 'sponge_plugins' or something to contain your sponge mods. I don't particularly think it's wise to have mods and plugins all in one directory. Some forge servers have a lot of mods, and some bukkit servers have a lot of plugins, I can see it being a hassle for server owners to have to try and distinguish what mods and what plugins they have installed.

**Comment by progwml6** [comment]
Users always put things where they don't belong we will be using one directory

**Comment by KieronWiltshire** [comment]
Well, care to explain why? because at the moment, I think it's pretty darn stupid.

**Comment by twizmwazin** [comment]
@progwml6 I feel like it would make sense to have this directory be configurable, defaulting to the mods directory. While this may not be an issue for SpongeVanilla users, Sponge users using many forge mods may want to keep Sponge plugins in a distinguished location.

**Comment by RobertHerhold** [comment]
If it were me, I would not implement this just for the sake of convenience. It should be up to server owners to keep their plugins and mods straight, and I don't think it's worth the while to try to change it. I believe that (at least for the Forge implementation), it is somewhat necessary to keep the plugins in the `mods` folder because the plugins are treated as mods by Forge, and are handled by FML. Someone please correct me if I am wrong, but I believe that is why both mods and plugins are put in the `mods` folder.

**Comment by progwml6** [comment]
@twizmwazin we will not be adding config options for this. 

@KieronWiltshire when in the past forge kept mods/coremods in different directories users always put things in the wrong ones and fed the resulting error reports upstream in droves
