### ISSUE TITLE
Made 1.8 Forge server with latest forge (1397) and console will not load.

### ISSUE THREAD

**Issue by SlipperySkater** [SpongePowered/Sponge#255]
Hello, I have recently made a 1.8 forge server using the forge (1397) and I have put sponge (sponge-1.8-1371-2.1DEV-433) into the mods folder and it does not seem to load the console, BUT when I load my 1.8 client and go to multiplayer, I see the server has started up but the console does not show up.

**Comment by ryantheleach** [comment]
The sponge version and forge version must match.

so Sponge-1.8-*1371*-2.1DEV-433 goes with forge (1371)

**Comment by Deamon5550** [comment]
We diabled the Minecraft server GUI see this commit 903a70b4c35d5a4828d8b8366cd6ccf8be468c5e.

**Comment by SlipperySkater** [comment]
Okay... is there going to be some kind of GUI so we know its running?

**Comment by twizmwazin** [comment]
@SlipperySkater You can interact with the server through the command line, there is no need for a gui.

**Comment by SlipperySkater** [comment]
How do I get to this command line?

**Comment by twizmwazin** [comment]
Start the server and it should appear. Do NOT double click the forge jar.

**Comment by SlipperySkater** [comment]
Nothing showed up, by starting it I just right clicked it and clicked open. I've no idea how else to start it.

**Comment by ryantheleach** [comment]
Start it *from* the command line instead of double clicking forge.

So either have a batch file, or open the terminal and write: " java -Xmx1024M -Xms1024M -jar minecraft_server.jar"

You will need to be in the correct directory however, so (assuming you are on windows) you can hold shift and right click inside the blank area of the folder (not on an icon) and click open command window here.

Where 1024M means 1 gigabyte of ram. replace this value with how much ram you want to dedicate to the forge server.

**Comment by ryantheleach** [comment]
https://docs.spongepowered.org/en/server/getting-started/launch-script.html for more information.
