### ISSUE TITLE
Across all our modpacks, entities are causing lag.

### ISSUE THREAD

**Issue by TheFlash787** [SpongePowered/Sponge#2602]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.2.1-RC4009
- Operating System: Ubuntu 18.04
- Plugins/Mods:
https://ptero.co/gozixivida.css

**Issue Description**
We've noticed that on all of our modpack servers that are using this SpongeForge version (or similar),  that there has been an absurd amount of lag caused by entities very often. If we clear entities with various commands and butchering, the lag still seems to persist. We found this by using Spark, where the profile can be found here: https://spark.lucko.me/#IJhjeh4dqo

Whilst there are some other things there causing some lag (this was taken on Omnifactory, where GT is present), entities are supposedly using over 50% of the ticktime. 
![image](https://user-images.githubusercontent.com/25883284/81486134-b0394580-924a-11ea-894c-4b46a0cc543f.png)

Is this something that has been reported before?
Thank you!

**Comment by clienthax** [comment]
It's definitely something I have seen happening on my own servers for a while

**Comment by Time6628** [comment]
Can confirm this issue as well.

**Comment by kristi71111** [comment]
Same here.

**Comment by gabizou** [comment]
I can't see this as a Sponge issue specifically, so I'll keep this issue closed unless a culprit within Sponge's system is provided as the cause of lag. Reviewing the spark results, there's *not much that sponge is doing* to cause or add on to lag. Even if you took into consideration the processing percentage of the entity tick from `TrackingUtil.tickEntity`, there's a limited amount of any particular result that we can gain. 

If there was for example a more in-depth profiling result with something like YourKit that gave us a truly exploreable profiling result, then maybe we can investigate further, but as is, the profiling results are rather limited to identify *what* is adding to lag (not discounting lag, just we're talking about code boundaries that are micro-optimizations that are down to the couple hundred of nano seconds by the volume of calls to some methods) As an example of what was considered in the past was the optimization to improve main thread checks, which is now something as simple as a field and `Thread.currentThread()` equality instance check, which is no doubt getting native compiled by the JVM.

I'd encourage continued discussion, but I don't have enough details as is to warrant it being an *open issue on SpongeCommon itself*.

**Comment by gabizou** [comment]
@bigenergy Because you're seeming to not understand what a profiling result means or how to interpret one, *no amount of code will ever have 0% time efficiency when a profiler performs it's calculations*


![](https://user-images.githubusercontent.com/17977139/83698129-52a9d600-a609-11ea-8787-f0e55a828214.png)

Your screenshot is also equally useless at providing anything because you're fundamentally not understanding what the actual cost of running a game physics engine with logical method side effects. 

The PhaseTracker is unique in a code sense because it gathers logical operation requests (methods to be called given some context, like a block breaking, an entity colliding with a block, an entity performing multiple block changes, and each of those blocks performing other side effects) to be queued for an event that would suggest to plugins saying "Hey, given this context of information, these blocks are gonna change at those coordinates with this set of new blocks, and they might have their own side effects if you allow the changes." After that event is done, then the side effects are actually performed (side effectual methods actually called with their originally intended contexts). The key is that all of this has to be done on the completion of the entity's "tick", which is unilaterally wrapped in the `PhaseContext.close()` (or if you open up nesting, `UnwrappingState.unwind`), but you'd still see the various methods being called, almost entirely invisibly *because it's down to as small of an operational gap as possible*.

I've been asking for better profiling *snapshots* not *screenshots* for a longer duration with truer profiling tools (like YourKit, free trial for anyone), but so far either no one has provided such results, or other issues were being fixed. **I'd be happy to eliminate the profiling bias by even inlining the changes that Sponge makes to the overall game physics methods**, but as many people know at this point, many core mods depend on Sponge not changing it's injections because otherwise their targeted injections no longer work.
