### ISSUE TITLE
Implement WorldProperties

### ISSUE THREAD

**Issue by loganspeck** [SpongePowered/Sponge#292]
Attempting to mess with world time. I have not tested whether or not it is just time or all of the properties of worlds, although the following seems to have no effect:
`world.getProperties().setWorldTime(time);`

**Comment by Deamon5550** [comment]
`getProperties()` returns an instance of minecraft's WorldInfo which has our WorldProperties mixed in properly and the setWorldTime method sets the time with in the WorldInfo properly. I expect the issue lies in the world time from world info not being used by the world, or being misinterpreted as to its actual function and this method will need to update the world as well as the properties.

**Comment by loganspeck** [comment]
@Deamon5550 Good to know, thanks for the reply!

**Comment by bloodmc** [comment]
@loganspeck Setting world time is working properly. You are probably attempting to change the time when it has reached its limit so it does nothing. Do this as a simple test 

1. /time set day
2. Set the time to 1000 using setWorldTime through our API.

The result should be night time.

**Comment by loganspeck** [comment]
@bloodmc You're entirely correct, my bad. This method is indeed working as intended.
