### ISSUE TITLE
DamageEntityEvent regression

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/Sponge#3042]
**I am currently running**
- SpongeVanilla version: 1.12.2-7.2.3-RC373
- Java version: 1.8.0_232
- Operating System: Windows 10

**Issue Description**
Commit 4c3a4d4 introduced an **important** regression of `DamageEntityEvent`. Before this commit, cancelling the event was also stopping all damage related mechanisms such as: knockback, animals running, pigman getting angry, hurt time, hurt resistant time, entity getting on fire if hit by a flame arrow, etc. Now cancelling the event is just equivalent as setting the damage to 0, but there is no way using the API to stop all the previous mechanisms. I weigh the word "important" because this issue affects protection plugins and has a huge impact on pvp / pve servers.

**Comment by dualspiral** [comment]
This is problematic one way or another, because we've now got Forge behaviour, but now we have this issue occurring instead. Rock and a hard place.

[What I suggest we do is bypass up to here](https://github.com/SpongePowered/SpongeCommon/blob/4c3a4d4436178ae61e601611a6829f82d3dee60c/src/main/java/org/spongepowered/common/mixin/core/entity/EntityLivingBaseMixin.java#L547). This will mean that FirstAid will keep working, but all other damage related effects are bypassed.

**Comment by dualspiral** [comment]
Actually, no, I know what's happened.

[This original fix is wrong](https://github.com/SpongePowered/SpongeCommon/commit/e53011124b96d50b88aec42b9d28dcc9d5e086a3), in that it cancels everything if the damage is zero. In Forge, the method then continues, so having returned true there means that Forge behaviour would be followed through the method.

This meant that I misidentified the fix to FirstAid, which should have been to simply flip that boolean to `true` and instead ignored the result.

I'll put up a PR shortly that I will need testing.
