### ISSUE TITLE
Activation Ranges Broken

### ISSUE THREAD

**Issue by kristi71111** [SpongePowered/Sponge#3109]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.2.4-RC4058
- Forge version: 14.23.5.2854
- SpongeVanilla version: N/A
- Java version: 251-b08
- Operating System: Windows 10

- Plugins/Mods:
**Mods (7):** Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, SpongeForge
**Plugins (7):** Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, BaconLottery, EconomyLite, LuckPerms

**Issue Description**
Upon updating to 1.12.2-2838-7.2.4-RC4061 entity activation ranges are still not being respected. As seen in the video below. I believe the same issue is present for tile activation ranges however I did not test that. From my understanding it seems like you need to get in the activation range at least once per load to set their state correctly. So if we take into account someone flying fast around the map and loading chunks however never triggering the activation range it can be a huge problem to performance. I will record a video of it later.
Related https://github.com/SpongePowered/SpongeCommon/issues/3081
**Sponge config:** <https://pastebin.com/j8dNJcBh>

**Comment by dualspiral** [comment]
> From my understanding it seems like you need to get in the activation range at least once per load to set their state correctly.

As I see it, exactly correct. [This is the problem line](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/entityactivation/entity/EntityMixin_Activation.java#L44), the default actication is true, and with lazily initialising activation states, everything is activated until, ironically, you get in range to "activate" it normally.

Two potential fixes:

* Flip this default to `false`, but there might be entities that we shouldn't be doing that with, in which case,
* Revert lazy activation state setting for entities (so 23642ed024879f3a65fab3a4d26b1b3b86e32ec8 and f8292061109be8880205771a1860290f3785c36a).

I don't think TEs are affected by this because their activation state seems to be set when it's loaded.

**Comment by dualspiral** [comment]
I was talking to @gabizou about this and we're just going to revert the lazy asssignment. I don't think there is a huge hit from doing it when the entity is created and it certainly beats having activated entities until someone flies by.

**Comment by kristi71111** [comment]
> I was talking to @gabizou about this and we're just going to revert the lazy asssignment. I don't think there is a huge hit from doing it when the entity is created and it certainly beats having activated entities until someone flies by.

Cheers I'll be looking forward to seeing this reverted.
