### ISSUE TITLE
"Trying to add entity with duplicated UUID" when placing Armor Stand

### ISSUE THREAD

**Issue by masagameplay** [SpongePowered/Sponge#3489]
**I am currently running**
- SpongeVanilla version: Latest (https://github.com/SpongePowered/Sponge/commit/aca662a49be95357dfcc8c7b53edb867d91f7b53) from Git
- Java version:  11.0.11/64-bit (AdoptOpenJDK)
- Operating System: Windows 10

**Issue Description**
When I place down Armor Stand (I took it from creative inventory), console prints:
```
[Server thread/WARN]: Trying to add entity with duplicated UUID 4452daef-481f-406c-8484-8c26af819054. Existing minecraft:armor_stand#1073, new: minecraft:armor_stand#1073
```

**Comment by dualspiral** [comment]
This is a Vanilla bug, at least in 1.16.5.

The problem is at `ArmorStandItem`, lines 48 and 52. Line 48 spawns in all the passengers and the armor stand itself (`addFreshEntityWithPassengers`, calls `Entity#getSelfAndPassengers`), line 52 tries to spawn in the stand again `addFreshEntity`.

This isn't a problem in 1.17.1, they move the `addFreshEntityWithPassengers` call to where `add`  is in 1.16.5.

**Comment by dualspiral** [comment]
For reference: https://bugs.mojang.com/browse/MC-196638
