### ISSUE TITLE
LoadWorldEvent & UnloadWorldEvent is not fired at startup

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/Sponge#3557]
**I am currently running**

- SpongeVanilla version: e0ecf137
- Java version: OpenJDK "16.0.1" 2021-04-20
- Operating System: KDE neon 5.23

**Issue Description**

The `LoadWorldEvent` and `UnloadWorldEvent` is not fired at startup. Judging by the code these events are only fired when worlds manually loaded/unloaded via `WorldManager`.

**Comment by Faithcaio** [comment]
Loading at startup is handled by us in `SpongeWorldManager` so that works now.

As for unload I am not sure...
We fire it on manual unload before saving and closing the world. (Note that we also have a `SaveWorldEvent.Pre/Post`)

We could fire an unload event for all active worlds before saving when shutting down the server.

Opinions?

**Comment by dualspiral** [comment]
Seems reasonable to me, the worlds _are_ being unloaded after all.

**Comment by Zidane** [comment]
Yes that is fine to fire the unload then.
