### ISSUE TITLE
ServerPlayer#closeInventory() doesn't work correctly

### ISSUE THREAD

**Issue by avaruus1** [SpongePowered/Sponge#3639]
### Affected Product(s)

SpongeVanilla

### Version

1.16.5-8.0.0-RC1077

### Operating System

Linux/5.15.15-xanmod1-tt-1 (amd64)

### Java Version

17.0.1/64-bit

### Plugins/Mods

```shell
Just my test plugin
```

### Describe the bug

Calling `ServerPlayer#closeInventory()` doesn't appear to send the container close packet to the player. As far as the server is aware, the inventory is indeed closed and any changes the player makes after the method is called do not persist.

As a workaround, you can send the `ClientboundContainerClosePacket` manually after calling the method to achieve the expected behavior.

**Comment by JBYoshi** [comment]
I think I found the problem. [`closeInventory()`](https://github.com/SpongePowered/Sponge/blob/fbc07e07e636a744815362f19c7e4d52318b6edf/src/mixins/java/org/spongepowered/common/mixin/inventory/api/server/level/ServerPlayerMixin_Inventory_API.java#L80) incorrectly states that the closing is triggered by the client instead of the server, so it doesn't think the client needs to know about any state changes. This should be a quick fix.
