### ISSUE TITLE
Better Minecraft Not Working with spongeforge

### ISSUE THREAD

**Issue by misterrevo** [SpongePowered/Sponge#3771]
### Affected Product(s)

SpongeForge

### Version

spongeforge-1.16.5-36.2.5-8.1.0-RC1188-universal

### Operating System

Linux

### Java Version

17

### Plugins/Mods

```shell
Better Minecraft
```

### Describe the bug

Sponge not running

### Link to logs

https://paste.gg/p/anonymous/25036357e9ec4b93a128c2b53a177ea6

**Comment by gabizou** [comment]
[Workaround](https://github.com/team-abnormals/blueprint/commit/df4932960266f2e30a541097811193c17d1bb339)  already fixed with a newer abnormals_core version, the patched version can be found here: https://cdn.discordapp.com/attachments/406987481825804290/949798054117122058/abnormals_core-1.16.5-3.3.1.jar
