### ISSUE TITLE
Command are not known with Sponge 10

### ISSUE THREAD

**Issue by Elikill58** [SpongePowered/Sponge#3775]
### Affected Product(s)

SpongeVanilla

### Version

1.19.2-10.0.0-RC1191

### Operating System

Windows

### Java Version

Java 17

### Plugins/Mods

```shell
any plugin with command
```

### Describe the bug

All command result with this log : 
```
Unknown or incomplete command, see below for error
cmd<--[HERE]
```
It seems to be present only with 1.19. Even with the Sponge test plugin, the error appear (with for example the cmd `rawcommandtest`)

**Comment by Faithcaio** [comment]
MC now parses all commands before passing it to the dispatcher (probably to be able to verify signed messages)
see `ServerGamePacketListener#performChatCommand` calling
`SpongeCommandDispatcher#execute(ParseResult)` now instead of
`SpongeCommandDispatcher#execute(StringReader, CommandSourceStack)` 



Raw Commands do not provide a Node for parsing atm. as such it thinks the command does not exist.
