### ISSUE TITLE
Cancelling a `InteractBlockEvent` affecting a Command Block gives a broken Command Block UI

### ISSUE THREAD

**Issue by carbotaniuman** [SpongePowered/Sponge#3801]
### Affected Product(s)

SpongeVanilla

### Version

1.16.5-8.1.0-RC1235

### Operating System

Windows

### Java Version

17.0.2/64-bit (Eclipse Adoptium)

### Plugins/Mods

```shell
None (other than my own)
```

### Describe the bug

```
@Listener
public void test(InteractBlockEvent event, @First ServerPlayer p) {
    event.setCancelled(true);
}
```

![image](https://user-images.githubusercontent.com/41451839/208767092-26a6e7e6-3258-48a0-a5b7-61cb9871171a.png)

I expect the command block UI to not open, but instead it opens but appears to be invalid (none of the buttons work and the autocomplete dialog is perpetually on.

**Comment by aromaa** [comment]
The command block UI is opened client side and there is no way to prevent that from the server. The UI is already grayed out due to the server not responding to the request and this seems enough to me. Technically we could use the container close packet to force close the UI afterwards but I don't think its worth it to special case it.
