### ISSUE TITLE
Interacting with an item removes fall damage

### ISSUE THREAD

**Issue by avaruus1** [SpongePowered/Sponge#3837]
### Affected Product(s)

SpongeVanilla

### Version

1.19.4-10.0.0-RC1304

### Operating System

Linux/6.2.8-zen1-1-zen

### Java Version

18.0.1/64-bit

### Plugins/Mods

```shell
-
```

### Describe the bug

It seems that a player can completely remove fall damage by interacting with an item.

To reproduce:
1. Place any item in main or off hand
2. Hold right click
3. Jump down from a high place

This issue also seems to exist when using 1.19.4 client on API-8 server, when using a plugin like ViaVersion to allow newer clients to connect.

**Comment by aromaa** [comment]
Why this is happening is due to the modern client sending a PosRot packet before the interaction. When you are falling down the client is sending the current position every tick so we don't end up starting a phase tracker capturing [and set the ignoreMovementCapture to true.](https://github.com/SpongePowered/Sponge/blob/fe248146305cbadd4a2e920605d32a4a09788a3e/src/main/java/org/spongepowered/common/event/tracking/phase/packet/PacketPhaseUtil.java#L215)

This seems to have some interesting side effect that causes us to use wrong coordinates when calculating the movement packet and makes the server believe we gained upwards momentum and resets the falling distance.
