### ISSUE TITLE
TPS drop when there's only a few players (from 20 tps to 1 tps)

### ISSUE THREAD

**Issue by kasdo** [SpongePowered/Sponge#3870]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.1.0-RC1352-universal

### Operating System

Linux

### Java Version

1.8.0_212/64-bit

### Plugins/Mods

```shell
Mods: pixelmon, BiomesOPlenty, BooshelfForge, chiselandhabits, WAWLA, costumes, ironchests, placebo, selene. clumps, fastfurnace, fastworkbench, ferritecore, notenoughcrashes, spark, starlight, storagedrawers, treechop, worldedit

Plugins: ChatManager, CommandPack, GTS, Impactor, LocaleAPI, LuckPerms, RegionGuard, TablistBoard
```

### Describe the bug

Server tps went down from 20 to 1 when there are only a few players online
There's a log from spark when it was 12 +- tps, when it got 1 tps I couldn't make another spark report
https://spark.lucko.me/LUKuZhYOOX

A log file wasn't created so I uploaded another one when I made a restart when the server had 12 tps

### Link to logs

https://paste.anfanik.me/arononejoz.sql

**Comment by kasdo** [comment]
I've just found the log when it's 1 tps and I tried to stop the server. Yes, I couldn't do that so I killed the process
https://paste.anfanik.me/dutasofugi.yaml

I have the same modpack on mohist server and there's no an issue like that

**Comment by Yeregorix** [comment]
I identified two major causes of lags in your report: 
- RegionGuard (~20% tick time). Basically the plugin is creating a new entity snapshot on each move event `event.entity().createSnapshot().world()` ([source](https://github.com/SawFowl/RegionGuard/blob/90bd4b21e85e73374d2bbcc830ecb78520aa07c2/src/main/java/sawfowl/regionguard/listeners/EntityMoveListener.java#L61)) which should be replaced by `((ServerWorld) event.entity().world()).key()`. Contact the plugin author.
- Pixelmon (at least 10% tick time). This mod is known to be very laggy mainly because it's spawning many entities. There isn't much you can't do about it. Maybe trying lowering spawn rate in Pixelmon settings or maybe take a look at Sponge entity activation range.

**Comment by kasdo** [comment]
Spawn rate is 3-4 times less then it is as common
Thanks about information about the plugin, I will try find the way to fix it with the developer
