### ISSUE TITLE
SpongeForge on NeoForge 1.20

### ISSUE THREAD

**Issue by Sam-Chai** [SpongePowered/Sponge#3887]
### Is this request specific to one implementation of Sponge?

Yes, only SpongeForge

### Sponge Version

1.20

### What are you requesting?

Is it possible to support NeoForge on 1.20 for SpongeForge? they look promising. And now, the NeoForge don't have a plugin server core. SpongeForge is expected to be the first.

**Comment by mosemister** [comment]
It has been internally discussed and publicly announced on SOS. Essentially the main target of forge could swap to NeoForge, but its too soon to tell. 

We need sponge forge 1.19.4 before we discuss it again. 

Its very unlikely that we would support forge and neoforge due to man power, but there is a small chance for both to be supported, depends on how different neo forge is to regular forge

**Comment by Sam-Chai** [comment]
> It has been internally discussed and publicly announced on SOS. Essentially the main target of forge could swap to NeoForge, but its too soon to tell. 
> 
> 
> 
> We need sponge forge 1.19.4 before we discuss it again. 
> 
> 
> 
> Its very unlikely that we would support forge and neoforge due to man power, but there is a small chance for both to be supported, depends on how different neo forge is to regular forge

I look forward to spongeforge's performance on higher MC version like 1.19 and 1.20. The regular forge server core has a huge lagg problem and bukkit hybrid core has some crash and unstable enough. In higher forge server, sponge is hopeful.

**Comment by ghost** [comment]
I can already imagine the amalgamation of Fabric, Forge, and Plugins - keep us up to date with your progress! :D

**Comment by Yeregorix** [comment]
We are going to officially support NeoForge.
You can follow progress on this PR : https://github.com/SpongePowered/Sponge/pull/4134
