### ISSUE TITLE
Transition to Neoforge

### ISSUE THREAD

**Issue by Outfit8TSB** [SpongePowered/Sponge#4113]
### Is this request specific to one implementation of Sponge?

Yes, only SpongeForge

### Sponge Version

1.20.4+

### What are you requesting?

SpongeForge have to make a Transition to Neoforge.

it's been a while, since the Neoforge Broken Out from forge, we have to note that the following: Neoforge No longer supports forge mods, trying to use SpongeForge on Neoforge is Nearly Impossible as this. we have a better point that the more mods will move on to Neoforge. 

We addressed the problem of The Geyser Server Admins, wanting to make a Modded sponge Server still have to keep using Geyser-Standalone if they want to make a Geyser Server. this transition is Necessary as the forge Mods are transitioning to Neoforge.

Forge Downfall has begun. Please Transition it, otherwise, the SpongeAPI Users can't use More Mods and have to stay with Bukkit-Neoforge Hybrid Servers. Many Server-side mods are here, but they are still unfamous.

**Comment by SawFowl** [comment]
Confirming the problem. Recently I made some [statistics on mods for 1.21](<https://gist.github.com/SawFowl/568c8cf371d044e1417d281433b0cca5>). 
On version 1.20.* switching to NeoForge makes no sense in my opinion, but on version 1.21 the situation is just the opposite and switching to NeoForge becomes actually necessary. Without it, there is no point in Sponge.

**Comment by Outfit8TSB** [comment]
yes. Forge's Downfall has already begun. There is absolutely No way to run Geyser with SpongeAPI Environment.
GeyserMC/Geyser#3781 was intended to replace Geyser-Sponge in favor of Spongeforge Users and forge users.
if you absolutely want to use Geyser with Sponge, 
all they have to do is:
1. use Geyser-Standalone: This is only choice using Geyser with SpongeAPI.
2. use Youer: this is a necessary when there is no choice, Use Server side mods. Example: EssentialsX -> FTB Essentials & FTB Chunks(EssentialsXAntiBuild)
3. Spongeforge's Transition to Neoforge. Neoforge is a Replacement for Forge. Mohist(Likely compatible with Bukkit) has a Neoforge Branch, Named Youer. known as MohistNeo. as forge is now fallen, and Sponges have the Alternatives for Bukkit Plugins. like Nucleus(EssentialsX and Bssentials-Bukkit) and More. 

it's become a hard decision between Minecraft Community as the Modding and Plugin Community become star wars like situation.
Forge's Tyranny, LexForge-Neoforge Split, and we have come here. SpongeForge's Complete Transition to LexForge to NeoForge. 

This Comment will be Republished as a Korean Language after 5 minutes as the Korean Sponge Users May Don't know this.

**Comment by Outfit8TSB** [comment]
Recently i saw your statistic and i saw one comment related to masha and bear
The bear rages for whole video and i saw masha for 2 sec
I think that bear looks like @LexManos

**Comment by Zidane** [comment]
I've deleted comments that elect to name calling or attacks on members of the community. Our issue tracker is not the place for it and we will not allow them to occur. If you comment again with that, you will be banned.

Please stick solely to the merits of this potential transition and nothing more.

**Comment by Outfit8TSB** [comment]
okay, sorry. i was supposed to address the OldForge's Downfall, Not Insulting Someone, Whoops.

**Comment by Outfit8TSB** [comment]
reading whole Neoforge Repository for a Forge Classes, ill brb

**Comment by Zidane** [comment]
While I have closed the PR (please review and read my reasons), I won't close this issue. We welcome the discussion especially as it helps to gauge true interest. So long, as stated above, this remains civil without attacks on any community member.

**Comment by SawFowl** [comment]
I'd like to make a point about PR.
I can't call replacing imports a big job. And can it really be called any work? When I made any PR in Sponge, I would check to see if my change would work. That is, I compiled the code and tested how it worked. My PRs were accepted as a result. The operation performed seems to have been done in a notepad. I can't explain [this](<https://github.com/Outfit8TSB/Sponge/blob/ecbd3a6c6b1e9d1b1d44c88b477e3d312dd33e51/forge/src/main/java/org/spongepowered/forge/hook/ForgeChannelHooks.java>) change otherwise. This is not work, but hackwork and banal hype.

Now as for the lack of an official decision on a possible switch to NeoForge.
I and most of the servers admins I've talked to don't see the point in supporting LexForge, since that mod loader is already effectively dying, they'd rather use NeoForge. The rest either use Fabric, or they don't care what to use and even vanilla(Spigot/Paper/etc) with datapacks will suit them.
As for me specifically, I can say that without this transition I see no point for me in further updating my plugins on Sponge and I will have to turn them into mods on NeoForge, I will simply have no choice but to do so. I will finish upgrading my plugins to API12 soon, but I doubt I will have any point in maintaining them in the future.

I can also say one more thing about Fabric. I don't see the point of supporting it as a server solution. This loader has many limitations and disadvantages, which can of course be mitigated, but it would be too much work. It's not worth it.

**Comment by Outfit8TSB** [comment]
ok, we will wait.

**Comment by Yeregorix** [comment]
We are going to officially support NeoForge.
You can follow progress on this PR : https://github.com/SpongePowered/Sponge/pull/4134

**Comment by Outfit8TSB** [comment]
closing in favor of #4134
